import type { KTOperative } from './killteam-data';

export const MORE_ROSTERS: Record<string, KTOperative[]> = {
  'Blooded': [
    { id: '', faction: 'Blooded', name: 'Traitor Chieftain', role: 'leader', movement: 6, apl: 3, groupAct: 1, defense: 3, save: 5, wounds: 12, weapons: [{ name: 'Bolt Pistol', type: 'ranged', attacks: 4, skill: 3, normalDmg: 3, critDmg: 4 }, { name: 'Brutal Axe', type: 'melee', attacks: 4, skill: 3, normalDmg: 4, critDmg: 5 }], abilities: ['Command', 'Dark Blessing: 5+ invuln'], aiType: 'tactical' },
    { id: '', faction: 'Blooded', name: 'Traitor Enforcer', role: 'fighter', movement: 6, apl: 2, groupAct: 1, defense: 3, save: 5, wounds: 8, weapons: [{ name: 'Laspistol', type: 'ranged', attacks: 4, skill: 4, normalDmg: 2, critDmg: 3 }, { name: 'Trench Club', type: 'melee', attacks: 4, skill: 4, normalDmg: 3, critDmg: 4 }], abilities: ['Discipline: Nearby allies reroll 1s'], aiType: 'tactical' },
    { id: '', faction: 'Blooded', name: 'Traitor Flenser', role: 'fighter', movement: 6, apl: 2, groupAct: 1, defense: 3, save: 5, wounds: 7, weapons: [{ name: 'Flensing Blades', type: 'melee', attacks: 5, skill: 3, normalDmg: 3, critDmg: 5, special: ['Rending'] }], abilities: ['Frenzy: +1 attack on charge'], aiType: 'aggressive' },
    { id: '', faction: 'Blooded', name: 'Traitor Gunner', role: 'gunner', movement: 6, apl: 2, groupAct: 1, defense: 3, save: 5, wounds: 7, weapons: [{ name: 'Plasma Gun', type: 'ranged', attacks: 4, skill: 4, normalDmg: 5, critDmg: 6, special: ['Hot'] }, { name: 'Gun Butt', type: 'melee', attacks: 3, skill: 4, normalDmg: 2, critDmg: 3 }], abilities: ['Overcharge'], aiType: 'tactical' },
    { id: '', faction: 'Blooded', name: 'Traitor Sharpshooter', role: 'gunner', movement: 6, apl: 2, groupAct: 1, defense: 3, save: 5, wounds: 7, weapons: [{ name: 'Long-las', type: 'ranged', attacks: 4, skill: 3, normalDmg: 3, critDmg: 4, special: ['Silent', 'Heavy'] }, { name: 'Bayonet', type: 'melee', attacks: 3, skill: 4, normalDmg: 2, critDmg: 3 }], abilities: ['Marksman'], aiType: 'defensive' },
    { id: '', faction: 'Blooded', name: 'Traitor Trooper', role: 'fighter', movement: 6, apl: 2, groupAct: 2, defense: 3, save: 5, wounds: 7, weapons: [{ name: 'Lasgun', type: 'ranged', attacks: 4, skill: 4, normalDmg: 2, critDmg: 3 }, { name: 'Bayonet', type: 'melee', attacks: 3, skill: 4, normalDmg: 2, critDmg: 3 }], abilities: ['Expendable'], aiType: 'tactical' },
  ],
  'Kommandos': [
    { id: '', faction: 'Kommandos', name: 'Kommando Nob', role: 'leader', movement: 6, apl: 3, groupAct: 1, defense: 3, save: 5, wounds: 14, weapons: [{ name: 'Slugga', type: 'ranged', attacks: 4, skill: 4, normalDmg: 3, critDmg: 4 }, { name: 'Power Klaw', type: 'melee', attacks: 4, skill: 4, normalDmg: 5, critDmg: 7, special: ['Brutal'] }], abilities: ['Waaagh!: +1 attack melee', 'Kunnin Plan'], aiType: 'aggressive' },
    { id: '', faction: 'Kommandos', name: 'Kommando Breacha Boy', role: 'fighter', movement: 6, apl: 2, groupAct: 1, defense: 3, save: 5, wounds: 12, weapons: [{ name: 'Breacha Ram', type: 'melee', attacks: 4, skill: 3, normalDmg: 5, critDmg: 6, special: ['Stun'] }], abilities: ['Smash Through: Ignore terrain'], aiType: 'aggressive' },
    { id: '', faction: 'Kommandos', name: 'Kommando Dakka Boy', role: 'gunner', movement: 6, apl: 2, groupAct: 1, defense: 3, save: 5, wounds: 12, weapons: [{ name: 'Big Shoota', type: 'ranged', attacks: 5, skill: 4, normalDmg: 3, critDmg: 4, special: ['Fusillade'] }, { name: 'Choppa', type: 'melee', attacks: 4, skill: 3, normalDmg: 4, critDmg: 5 }], abilities: ['Dakka Dakka'], aiType: 'tactical' },
    { id: '', faction: 'Kommandos', name: 'Kommando Slasha Boy', role: 'fighter', movement: 6, apl: 2, groupAct: 1, defense: 3, save: 5, wounds: 12, weapons: [{ name: 'Slugga', type: 'ranged', attacks: 4, skill: 4, normalDmg: 3, critDmg: 4 }, { name: 'Choppa', type: 'melee', attacks: 4, skill: 3, normalDmg: 4, critDmg: 5 }], abilities: ['Waaagh!'], aiType: 'aggressive' },
    { id: '', faction: 'Kommandos', name: 'Kommando Snipa Boy', role: 'gunner', movement: 6, apl: 2, groupAct: 1, defense: 3, save: 5, wounds: 12, weapons: [{ name: 'Snipa Rifle', type: 'ranged', attacks: 4, skill: 4, normalDmg: 3, critDmg: 5, special: ['Silent', 'Heavy'] }, { name: 'Knife', type: 'melee', attacks: 3, skill: 3, normalDmg: 3, critDmg: 4 }], abilities: ['Kunnin Aim'], aiType: 'defensive' },
    { id: '', faction: 'Kommandos', name: 'Kommando Grot', role: 'scout', movement: 6, apl: 2, groupAct: 1, defense: 3, save: 6, wounds: 5, weapons: [{ name: 'Grot Blasta', type: 'ranged', attacks: 3, skill: 4, normalDmg: 2, critDmg: 3 }, { name: 'Knife', type: 'melee', attacks: 3, skill: 5, normalDmg: 2, critDmg: 3 }], abilities: ['Sneaky Git: Free dash', 'Expendable'], aiType: 'tactical' },
  ],
  'Legionaries': [
    { id: '', faction: 'Legionaries', name: 'Aspiring Champion', role: 'leader', movement: 6, apl: 3, groupAct: 1, defense: 3, save: 3, wounds: 14, weapons: [{ name: 'Bolt Pistol', type: 'ranged', attacks: 4, skill: 3, normalDmg: 3, critDmg: 4 }, { name: 'Power Fist', type: 'melee', attacks: 4, skill: 3, normalDmg: 5, critDmg: 7, special: ['Brutal'] }], abilities: ['Dark Pact: Choose Khorne/Nurgle/Slaanesh/Tzeentch bonus', 'Let the Galaxy Burn'], aiType: 'aggressive' },
    { id: '', faction: 'Legionaries', name: 'Chosen', role: 'fighter', movement: 6, apl: 3, groupAct: 1, defense: 3, save: 3, wounds: 13, weapons: [{ name: 'Boltgun', type: 'ranged', attacks: 4, skill: 3, normalDmg: 3, critDmg: 4 }, { name: 'Chainsword', type: 'melee', attacks: 4, skill: 3, normalDmg: 4, critDmg: 5 }], abilities: ['Hateful Assault'], aiType: 'aggressive' },
    { id: '', faction: 'Legionaries', name: 'Heavy Gunner', role: 'heavy', movement: 6, apl: 3, groupAct: 1, defense: 3, save: 3, wounds: 13, weapons: [{ name: 'Heavy Bolter', type: 'ranged', attacks: 5, skill: 3, normalDmg: 4, critDmg: 5, special: ['Heavy', 'Fusillade'] }, { name: 'Fists', type: 'melee', attacks: 3, skill: 3, normalDmg: 3, critDmg: 4 }], abilities: ['Suppressive Fire'], aiType: 'defensive' },
    { id: '', faction: 'Legionaries', name: 'Shrivetalon', role: 'fighter', movement: 6, apl: 3, groupAct: 1, defense: 3, save: 3, wounds: 13, weapons: [{ name: 'Bolt Pistol', type: 'ranged', attacks: 4, skill: 3, normalDmg: 3, critDmg: 4 }, { name: 'Flaying Knives', type: 'melee', attacks: 5, skill: 2, normalDmg: 3, critDmg: 5, special: ['Rending'] }], abilities: ['Torment: -1 APL to nearby enemies'], aiType: 'aggressive' },
    { id: '', faction: 'Legionaries', name: 'Balefire Acolyte', role: 'specialist', movement: 6, apl: 3, groupAct: 1, defense: 3, save: 3, wounds: 13, weapons: [{ name: 'Warpfire', type: 'ranged', attacks: 4, skill: 3, normalDmg: 4, critDmg: 5, special: ['Blast'] }, { name: 'Staff', type: 'melee', attacks: 4, skill: 3, normalDmg: 3, critDmg: 4 }], abilities: ['Sorcerous Bolt: Mortal wounds at range'], aiType: 'tactical' },
    { id: '', faction: 'Legionaries', name: 'Butcher', role: 'fighter', movement: 6, apl: 3, groupAct: 1, defense: 3, save: 3, wounds: 13, weapons: [{ name: 'Bolt Pistol', type: 'ranged', attacks: 4, skill: 3, normalDmg: 3, critDmg: 4 }, { name: 'Great Weapon', type: 'melee', attacks: 4, skill: 3, normalDmg: 5, critDmg: 7, special: ['Brutal'] }], abilities: ['Blood for the Blood God: Heal on kill'], aiType: 'aggressive' },
  ],
  'Wyrmblade': [
    { id: '', faction: 'Wyrmblade', name: 'Locus', role: 'leader', movement: 6, apl: 3, groupAct: 1, defense: 3, save: 5, wounds: 12, weapons: [{ name: 'Locus Blades', type: 'melee', attacks: 5, skill: 2, normalDmg: 4, critDmg: 6, special: ['Lethal 5+'] }], abilities: ['Preternatural Assassin', 'Bodyguard'], aiType: 'aggressive' },
    { id: '', faction: 'Wyrmblade', name: 'Neophyte Leader', role: 'leader', movement: 6, apl: 2, groupAct: 1, defense: 3, save: 5, wounds: 8, weapons: [{ name: 'Bolt Pistol', type: 'ranged', attacks: 4, skill: 4, normalDmg: 3, critDmg: 4 }, { name: 'Power Pick', type: 'melee', attacks: 4, skill: 4, normalDmg: 4, critDmg: 5 }], abilities: ['Cult Ambush', 'Command'], aiType: 'tactical' },
    { id: '', faction: 'Wyrmblade', name: 'Kelermorph', role: 'gunner', movement: 6, apl: 3, groupAct: 1, defense: 3, save: 5, wounds: 10, weapons: [{ name: 'Liberator Autostubs', type: 'ranged', attacks: 6, skill: 2, normalDmg: 3, critDmg: 4, special: ['Relentless'] }], abilities: ['Gunslinger: Shoot twice', 'Heroic Inspiration'], aiType: 'tactical' },
    { id: '', faction: 'Wyrmblade', name: 'Sanctus', role: 'gunner', movement: 6, apl: 3, groupAct: 1, defense: 3, save: 5, wounds: 10, weapons: [{ name: 'Sanctus Sniper', type: 'ranged', attacks: 4, skill: 2, normalDmg: 3, critDmg: 5, special: ['Silent', 'Piercing 1'] }, { name: 'Sanctus Blade', type: 'melee', attacks: 4, skill: 2, normalDmg: 4, critDmg: 5 }], abilities: ['Psychic Assassin', 'Soulsight'], aiType: 'defensive' },
    { id: '', faction: 'Wyrmblade', name: 'Neophyte Gunner', role: 'gunner', movement: 6, apl: 2, groupAct: 2, defense: 3, save: 5, wounds: 7, weapons: [{ name: 'Mining Laser', type: 'ranged', attacks: 4, skill: 4, normalDmg: 5, critDmg: 6, special: ['Heavy'] }, { name: 'Gun Butt', type: 'melee', attacks: 3, skill: 4, normalDmg: 2, critDmg: 3 }], abilities: ['Cult Ambush'], aiType: 'tactical' },
    { id: '', faction: 'Wyrmblade', name: 'Neophyte Hybrid', role: 'fighter', movement: 6, apl: 2, groupAct: 2, defense: 3, save: 5, wounds: 7, weapons: [{ name: 'Autogun', type: 'ranged', attacks: 4, skill: 4, normalDmg: 2, critDmg: 3 }, { name: 'Cult Knife', type: 'melee', attacks: 3, skill: 4, normalDmg: 2, critDmg: 3 }], abilities: ['Cult Ambush'], aiType: 'tactical' },
  ],
  'Void-Dancers': [
    { id: '', faction: 'Void-Dancers', name: 'Lead Player', role: 'leader', movement: 8, apl: 3, groupAct: 1, defense: 3, save: 6, wounds: 10, weapons: [{ name: 'Harlequin Kiss', type: 'melee', attacks: 5, skill: 2, normalDmg: 4, critDmg: 6, special: ['Lethal 5+', 'Piercing 1'] }], abilities: ['Flip Belt: Fly', 'Rising Crescendo: Free dash after fight', 'Domino Field: 4+ invuln'], aiType: 'aggressive' },
    { id: '', faction: 'Void-Dancers', name: 'Mime', role: 'fighter', movement: 8, apl: 2, groupAct: 1, defense: 3, save: 6, wounds: 8, weapons: [{ name: 'Harlequin Blade', type: 'melee', attacks: 5, skill: 2, normalDmg: 3, critDmg: 5, special: ['Lethal 5+'] }], abilities: ['Flip Belt', 'Veil of Tears: -1 to hit', 'Domino Field'], aiType: 'aggressive' },
    { id: '', faction: 'Void-Dancers', name: 'Player (Kiss)', role: 'fighter', movement: 8, apl: 2, groupAct: 1, defense: 3, save: 6, wounds: 8, weapons: [{ name: 'Shuriken Pistol', type: 'ranged', attacks: 4, skill: 2, normalDmg: 3, critDmg: 4, special: ['Rending'] }, { name: 'Harlequin Kiss', type: 'melee', attacks: 4, skill: 2, normalDmg: 4, critDmg: 6, special: ['Lethal 5+', 'Piercing 1'] }], abilities: ['Flip Belt', 'Rising Crescendo', 'Domino Field'], aiType: 'aggressive' },
    { id: '', faction: 'Void-Dancers', name: 'Player (Caress)', role: 'fighter', movement: 8, apl: 2, groupAct: 1, defense: 3, save: 6, wounds: 8, weapons: [{ name: 'Shuriken Pistol', type: 'ranged', attacks: 4, skill: 2, normalDmg: 3, critDmg: 4, special: ['Rending'] }, { name: 'Harlequin Caress', type: 'melee', attacks: 4, skill: 2, normalDmg: 3, critDmg: 5, special: ['Lethal 5+', 'Piercing 2'] }], abilities: ['Flip Belt', 'Rising Crescendo', 'Domino Field'], aiType: 'aggressive' },
    { id: '', faction: 'Void-Dancers', name: 'Death Jester', role: 'gunner', movement: 8, apl: 2, groupAct: 1, defense: 3, save: 6, wounds: 8, weapons: [{ name: 'Shrieker Cannon', type: 'ranged', attacks: 4, skill: 2, normalDmg: 4, critDmg: 5, special: ['Blast', 'Devastating 1'] }, { name: 'Blade', type: 'melee', attacks: 4, skill: 2, normalDmg: 3, critDmg: 4 }], abilities: ['Flip Belt', 'Cruel Amusement: Panic on kill', 'Domino Field'], aiType: 'tactical' },
  ],
};
