import type { ModelPreset } from './model-presets';

// Kill Team specific boxes and operatives
export const KILLTEAM_PRESETS: ModelPreset[] = [
  // Kill Team specific releases
  { name: 'Veteran Guardsmen', faction: 'Astra Militarum', unitType: 'Kill Team', defaultQty: 10 },
  { name: 'Kommandos Kill Team', faction: 'Orks', unitType: 'Kill Team', defaultQty: 10 },
  { name: 'Pathfinder Kill Team', faction: 'Tau Empire', unitType: 'Kill Team', defaultQty: 10 },
  { name: 'Novitiates', faction: 'Adepta Sororitas', unitType: 'Kill Team', defaultQty: 10 },
  { name: 'Corsair Voidscarred', faction: 'Aeldari', unitType: 'Kill Team', defaultQty: 10 },
  { name: 'Legionary Kill Team', faction: 'Chaos Space Marines', unitType: 'Kill Team', defaultQty: 6 },
  { name: 'Blooded Kill Team', faction: 'Chaos Space Marines', unitType: 'Kill Team', defaultQty: 10 },
  { name: 'Kasrkin Kill Team', faction: 'Astra Militarum', unitType: 'Kill Team', defaultQty: 10 },
  { name: 'Hand of the Archon', faction: 'Drukhari', unitType: 'Kill Team', defaultQty: 5 },
  { name: 'Exaction Squad', faction: 'Adeptus Arbites', unitType: 'Kill Team', defaultQty: 10 },
  { name: 'Nemesis Claw', faction: 'Chaos Space Marines', unitType: 'Kill Team', defaultQty: 5 },
  { name: 'Mandrakes Kill Team', faction: 'Drukhari', unitType: 'Kill Team', defaultQty: 5 },
  { name: 'Inquisitorial Agents', faction: 'Agents of the Imperium', unitType: 'Kill Team', defaultQty: 10 },
  { name: 'Fellgor Ravagers', faction: 'Chaos', unitType: 'Kill Team', defaultQty: 10 },
  { name: 'Hearthkyn Salvagers', faction: 'Leagues of Votann', unitType: 'Kill Team', defaultQty: 10 },
  { name: 'Hernkyn Yaegirs', faction: 'Leagues of Votann', unitType: 'Kill Team', defaultQty: 10 },
  { name: 'Phobos Strike Team', faction: 'Space Marines', unitType: 'Kill Team', defaultQty: 6 },
  { name: 'Scout Squad Kill Team', faction: 'Space Marines', unitType: 'Kill Team', defaultQty: 5 },
  { name: 'Intercession Squad', faction: 'Space Marines', unitType: 'Kill Team', defaultQty: 5 },
  { name: 'Plague Marines Kill Team', faction: 'Death Guard', unitType: 'Kill Team', defaultQty: 7 },
  { name: 'Wyrmblade', faction: 'Genestealer Cults', unitType: 'Kill Team', defaultQty: 10 },
  { name: 'Brood Coven', faction: 'Genestealer Cults', unitType: 'Kill Team', defaultQty: 10 },
  { name: 'Hierotek Circle', faction: 'Necrons', unitType: 'Kill Team', defaultQty: 5 },
  { name: 'Tomb World Kill Team', faction: 'Necrons', unitType: 'Kill Team', defaultQty: 10 },
  { name: 'Farstalker Kinband', faction: 'Tau Empire', unitType: 'Kill Team', defaultQty: 12 },
  { name: 'Gellerpox Infected', faction: 'Chaos', unitType: 'Kill Team', defaultQty: 7 },
  { name: 'Elucidian Starstriders', faction: 'Agents of the Imperium', unitType: 'Kill Team', defaultQty: 7 },
  { name: 'Warp Coven', faction: 'Thousand Sons', unitType: 'Kill Team', defaultQty: 5 },
  { name: 'Warpcoven Sorcerers', faction: 'Thousand Sons', unitType: 'Kill Team', defaultQty: 3 },
  { name: 'Hunter Clade', faction: 'Adeptus Mechanicus', unitType: 'Kill Team', defaultQty: 10 },

  // Named Characters - Space Marines
  { name: 'Roboute Guilliman', faction: 'Space Marines', unitType: 'Character', defaultQty: 1 },
  { name: 'Marneus Calgar', faction: 'Space Marines', unitType: 'Character', defaultQty: 1 },
  { name: 'Dante', faction: 'Space Marines', unitType: 'Character', defaultQty: 1 },
  { name: 'Ragnar Blackmane', faction: 'Space Marines', unitType: 'Character', defaultQty: 1 },
  { name: 'Azrael', faction: 'Space Marines', unitType: 'Character', defaultQty: 1 },
  { name: 'Tor Garadon', faction: 'Space Marines', unitType: 'Character', defaultQty: 1 },
  { name: 'Uriel Ventris', faction: 'Space Marines', unitType: 'Character', defaultQty: 1 },
  { name: 'Calsius', faction: 'Space Marines', unitType: 'Character', defaultQty: 1 },

  // More Space Marine units
  { name: 'Assault Squad', faction: 'Space Marines', unitType: 'Jump Infantry', defaultQty: 5 },
  { name: 'Bike Squad', faction: 'Space Marines', unitType: 'Mounted', defaultQty: 3 },
  { name: 'Attack Bike', faction: 'Space Marines', unitType: 'Mounted', defaultQty: 1 },
  { name: 'Land Speeder', faction: 'Space Marines', unitType: 'Vehicle', defaultQty: 1 },
  { name: 'Land Speeder Tornado', faction: 'Space Marines', unitType: 'Vehicle', defaultQty: 1 },
  { name: 'Invader ATV', faction: 'Space Marines', unitType: 'Vehicle', defaultQty: 1 },
  { name: 'Storm Speeder', faction: 'Space Marines', unitType: 'Vehicle', defaultQty: 1 },
  { name: 'Hammerfall Bunker', faction: 'Space Marines', unitType: 'Fortification', defaultQty: 1 },
  { name: 'Firestrike Servo-turret', faction: 'Space Marines', unitType: 'Vehicle', defaultQty: 1 },
  { name: 'Gladiator Reaper', faction: 'Space Marines', unitType: 'Vehicle', defaultQty: 1 },
  { name: 'Gladiator Valiant', faction: 'Space Marines', unitType: 'Vehicle', defaultQty: 1 },
  { name: 'Ironclad Dreadnought', faction: 'Space Marines', unitType: 'Vehicle', defaultQty: 1 },
  { name: 'Venerable Dreadnought', faction: 'Space Marines', unitType: 'Vehicle', defaultQty: 1 },
  { name: 'Contemptor Dreadnought', faction: 'Space Marines', unitType: 'Vehicle', defaultQty: 1 },
  { name: 'Infernus Squad', faction: 'Space Marines', unitType: 'Infantry', defaultQty: 5 },
  { name: 'Desolation Squad', faction: 'Space Marines', unitType: 'Infantry', defaultQty: 5 },
  { name: 'Sternguard Veterans', faction: 'Space Marines', unitType: 'Infantry', defaultQty: 5 },

  // More Guard
  { name: 'Attilan Rough Riders', faction: 'Astra Militarum', unitType: 'Mounted', defaultQty: 5 },
  { name: 'Ogryn Squad', faction: 'Astra Militarum', unitType: 'Infantry', defaultQty: 3 },
  { name: 'Wyvern', faction: 'Astra Militarum', unitType: 'Vehicle', defaultQty: 1 },
  { name: 'Taurox', faction: 'Astra Militarum', unitType: 'Vehicle', defaultQty: 1 },
  { name: 'Taurox Prime', faction: 'Astra Militarum', unitType: 'Vehicle', defaultQty: 1 },
  { name: 'Lord Solar Leontus', faction: 'Astra Militarum', unitType: 'Character', defaultQty: 1 },
  { name: 'Cadian Castellan', faction: 'Astra Militarum', unitType: 'Character', defaultQty: 1 },

  // More Orks
  { name: 'Squighog Boyz', faction: 'Orks', unitType: 'Mounted', defaultQty: 3 },
  { name: 'Warbikers', faction: 'Orks', unitType: 'Mounted', defaultQty: 3 },
  { name: 'Deffkoptas', faction: 'Orks', unitType: 'Vehicle', defaultQty: 3 },
  { name: 'Mek Gunz', faction: 'Orks', unitType: 'Vehicle', defaultQty: 1 },
  { name: 'Morkanaut', faction: 'Orks', unitType: 'Vehicle', defaultQty: 1 },
  { name: 'Beastsnagga Boyz', faction: 'Orks', unitType: 'Troops', defaultQty: 10 },
  { name: 'Tankbustas', faction: 'Orks', unitType: 'Infantry', defaultQty: 5 },
  { name: 'Ghazghkull Thraka', faction: 'Orks', unitType: 'Character', defaultQty: 1 },
  { name: 'Makari', faction: 'Orks', unitType: 'Character', defaultQty: 1 },

  // More Necrons
  { name: 'Hexmark Destroyer', faction: 'Necrons', unitType: 'Character', defaultQty: 1 },
  { name: 'Psychomancer', faction: 'Necrons', unitType: 'Character', defaultQty: 1 },
  { name: 'Chronomancer', faction: 'Necrons', unitType: 'Character', defaultQty: 1 },
  { name: 'Technomancer', faction: 'Necrons', unitType: 'Character', defaultQty: 1 },
  { name: 'Doom Scythe', faction: 'Necrons', unitType: 'Vehicle', defaultQty: 1 },
  { name: 'Night Scythe', faction: 'Necrons', unitType: 'Vehicle', defaultQty: 1 },
  { name: 'Tomb Blades', faction: 'Necrons', unitType: 'Mounted', defaultQty: 3 },
  { name: 'Convergence of Dominion', faction: 'Necrons', unitType: 'Fortification', defaultQty: 3 },
  { name: 'Silent King', faction: 'Necrons', unitType: 'Character', defaultQty: 1 },

  // More Tyranids
  { name: 'Maleceptor', faction: 'Tyranids', unitType: 'Monster', defaultQty: 1 },
  { name: 'Tervigon', faction: 'Tyranids', unitType: 'Monster', defaultQty: 1 },
  { name: 'Harpy', faction: 'Tyranids', unitType: 'Monster', defaultQty: 1 },
  { name: 'Hive Crone', faction: 'Tyranids', unitType: 'Monster', defaultQty: 1 },
  { name: 'Pyrovore', faction: 'Tyranids', unitType: 'Infantry', defaultQty: 1 },
  { name: 'Venomthropes', faction: 'Tyranids', unitType: 'Infantry', defaultQty: 3 },
  { name: 'Raveners', faction: 'Tyranids', unitType: 'Infantry', defaultQty: 3 },
  { name: 'Parasite of Mortrex', faction: 'Tyranids', unitType: 'Character', defaultQty: 1 },
  { name: 'Deathleaper', faction: 'Tyranids', unitType: 'Character', defaultQty: 1 },
  { name: 'Old One Eye', faction: 'Tyranids', unitType: 'Character', defaultQty: 1 },
  { name: 'Swarmlord', faction: 'Tyranids', unitType: 'Character', defaultQty: 1 },

  // More Tau
  { name: 'Coldstar Commander', faction: 'Tau Empire', unitType: 'Character', defaultQty: 1 },
  { name: 'Enforcer Commander', faction: 'Tau Empire', unitType: 'Character', defaultQty: 1 },
  { name: 'Darkstrider', faction: 'Tau Empire', unitType: 'Character', defaultQty: 1 },
  { name: 'Shadowsun', faction: 'Tau Empire', unitType: 'Character', defaultQty: 1 },
  { name: 'Piranhas', faction: 'Tau Empire', unitType: 'Vehicle', defaultQty: 1 },
  { name: 'Sky Ray', faction: 'Tau Empire', unitType: 'Vehicle', defaultQty: 1 },
  { name: 'Sun Shark Bomber', faction: 'Tau Empire', unitType: 'Vehicle', defaultQty: 1 },
  { name: 'Razorshark Strike Fighter', faction: 'Tau Empire', unitType: 'Vehicle', defaultQty: 1 },
  { name: 'Kroot Hounds', faction: 'Tau Empire', unitType: 'Beasts', defaultQty: 5 },
  { name: 'Krootox Riders', faction: 'Tau Empire', unitType: 'Mounted', defaultQty: 1 },

  // More Chaos
  { name: 'Vashtorr', faction: 'Chaos Space Marines', unitType: 'Character', defaultQty: 1 },
  { name: 'Daemon Prince', faction: 'Chaos Space Marines', unitType: 'Character', defaultQty: 1 },
  { name: 'Daemon Prince with Wings', faction: 'Chaos Space Marines', unitType: 'Character', defaultQty: 1 },
  { name: 'Cultist Mob', faction: 'Chaos Space Marines', unitType: 'Troops', defaultQty: 10 },
  { name: 'Dark Commune', faction: 'Chaos Space Marines', unitType: 'Character', defaultQty: 5 },
  { name: 'Chaos Spawn', faction: 'Chaos Space Marines', unitType: 'Beasts', defaultQty: 2 },
  { name: 'Bikers', faction: 'Chaos Space Marines', unitType: 'Mounted', defaultQty: 3 },
  { name: 'Predator', faction: 'Chaos Space Marines', unitType: 'Vehicle', defaultQty: 1 },
  { name: 'Vindicator', faction: 'Chaos Space Marines', unitType: 'Vehicle', defaultQty: 1 },
];
