export interface ModelPreset {
  name: string;
  faction: string;
  unitType: string;
  defaultQty: number;
  points?: number;
  forceOrg?: string;
}

const imperium: ModelPreset[] = [
  { name: 'Intercessors', faction: 'Space Marines', unitType: 'Battleline', defaultQty: 10, points: 160, forceOrg: 'Troops' },
  { name: 'Assault Intercessors', faction: 'Space Marines', unitType: 'Battleline', defaultQty: 10, points: 160, forceOrg: 'Troops' },
  { name: 'Heavy Intercessors', faction: 'Space Marines', unitType: 'Battleline', defaultQty: 5, points: 100, forceOrg: 'Troops' },
  { name: 'Tactical Squad', faction: 'Space Marines', unitType: 'Battleline', defaultQty: 10, points: 150, forceOrg: 'Troops' },
  { name: 'Infiltrators', faction: 'Space Marines', unitType: 'Battleline', defaultQty: 10, points: 180, forceOrg: 'Troops' },
  { name: 'Hellblasters', faction: 'Space Marines', unitType: 'Infantry', defaultQty: 5, points: 125, forceOrg: 'Elites' },
  { name: 'Bladeguard Veterans', faction: 'Space Marines', unitType: 'Infantry', defaultQty: 3, points: 90, forceOrg: 'Elites' },
  { name: 'Terminators', faction: 'Space Marines', unitType: 'Infantry', defaultQty: 5, points: 200, forceOrg: 'Elites' },
  { name: 'Sternguard Veterans', faction: 'Space Marines', unitType: 'Infantry', defaultQty: 5, points: 115, forceOrg: 'Elites' },
  { name: 'Eradicators', faction: 'Space Marines', unitType: 'Infantry', defaultQty: 3, points: 95, forceOrg: 'Heavy Support' },
  { name: 'Aggressors', faction: 'Space Marines', unitType: 'Infantry', defaultQty: 3, points: 110, forceOrg: 'Elites' },
  { name: 'Eliminators', faction: 'Space Marines', unitType: 'Infantry', defaultQty: 3, points: 75, forceOrg: 'Heavy Support' },
  { name: 'Scouts', faction: 'Space Marines', unitType: 'Battleline', defaultQty: 5, points: 65, forceOrg: 'Troops' },
  { name: 'Redemptor Dreadnought', faction: 'Space Marines', unitType: 'Walker', defaultQty: 1, points: 210, forceOrg: 'Elites' },
  { name: 'Ballistus Dreadnought', faction: 'Space Marines', unitType: 'Walker', defaultQty: 1, points: 140, forceOrg: 'Elites' },
  { name: 'Brutalis Dreadnought', faction: 'Space Marines', unitType: 'Walker', defaultQty: 1, points: 160, forceOrg: 'Elites' },
  { name: 'Repulsor', faction: 'Space Marines', unitType: 'Transport', defaultQty: 1, points: 195, forceOrg: 'Dedicated Transport' },
  { name: 'Repulsor Executioner', faction: 'Space Marines', unitType: 'Vehicle', defaultQty: 1, points: 230, forceOrg: 'Heavy Support' },
  { name: 'Impulsor', faction: 'Space Marines', unitType: 'Transport', defaultQty: 1, points: 105, forceOrg: 'Dedicated Transport' },
  { name: 'Gladiator Lancer', faction: 'Space Marines', unitType: 'Vehicle', defaultQty: 1, points: 160, forceOrg: 'Heavy Support' },
  { name: 'Land Raider', faction: 'Space Marines', unitType: 'Vehicle', defaultQty: 1, points: 260, forceOrg: 'Heavy Support' },
  { name: 'Stormraven Gunship', faction: 'Space Marines', unitType: 'Vehicle', defaultQty: 1, points: 260, forceOrg: 'Flyer' },
  { name: 'Captain', faction: 'Space Marines', unitType: 'Character', defaultQty: 1, points: 80, forceOrg: 'HQ' },
  { name: 'Captain in Terminator Armour', faction: 'Space Marines', unitType: 'Character', defaultQty: 1, points: 95, forceOrg: 'HQ' },
  { name: 'Librarian', faction: 'Space Marines', unitType: 'Character', defaultQty: 1, points: 75, forceOrg: 'HQ' },
  { name: 'Chaplain', faction: 'Space Marines', unitType: 'Character', defaultQty: 1, points: 65, forceOrg: 'HQ' },
  { name: 'Lieutenant', faction: 'Space Marines', unitType: 'Character', defaultQty: 1, points: 75, forceOrg: 'HQ' },
  { name: 'Apothecary', faction: 'Space Marines', unitType: 'Character', defaultQty: 1, points: 55, forceOrg: 'Elites' },
  { name: 'Ancient', faction: 'Space Marines', unitType: 'Character', defaultQty: 1, points: 55, forceOrg: 'Elites' },
  { name: 'Outriders', faction: 'Space Marines', unitType: 'Mounted', defaultQty: 3, points: 80, forceOrg: 'Fast Attack' },
  { name: 'Inceptors', faction: 'Space Marines', unitType: 'Jump Infantry', defaultQty: 3, points: 115, forceOrg: 'Fast Attack' },
  { name: 'Suppressors', faction: 'Space Marines', unitType: 'Jump Infantry', defaultQty: 3, points: 85, forceOrg: 'Fast Attack' },
  { name: 'Cadian Shock Troops', faction: 'Astra Militarum', unitType: 'Troops', defaultQty: 10 },
  { name: 'Kasrkin', faction: 'Astra Militarum', unitType: 'Infantry', defaultQty: 10 },
  { name: 'Leman Russ Battle Tank', faction: 'Astra Militarum', unitType: 'Vehicle', defaultQty: 1 },
  { name: 'Rogal Dorn Battle Tank', faction: 'Astra Militarum', unitType: 'Vehicle', defaultQty: 1 },
  { name: 'Chimera', faction: 'Astra Militarum', unitType: 'Vehicle', defaultQty: 1 },
  { name: 'Sentinel', faction: 'Astra Militarum', unitType: 'Walker', defaultQty: 1 },
  { name: 'Heavy Weapons Squad', faction: 'Astra Militarum', unitType: 'Infantry', defaultQty: 3 },
  { name: 'Baneblade', faction: 'Astra Militarum', unitType: 'Vehicle', defaultQty: 1 },
  { name: 'Company Commander', faction: 'Astra Militarum', unitType: 'Character', defaultQty: 1 },
  { name: 'Battle Sisters Squad', faction: 'Adepta Sororitas', unitType: 'Troops', defaultQty: 10 },
  { name: 'Retributors', faction: 'Adepta Sororitas', unitType: 'Infantry', defaultQty: 5 },
  { name: 'Seraphim', faction: 'Adepta Sororitas', unitType: 'Jump Infantry', defaultQty: 5 },
  { name: 'Repentia', faction: 'Adepta Sororitas', unitType: 'Infantry', defaultQty: 5 },
  { name: 'Exorcist', faction: 'Adepta Sororitas', unitType: 'Vehicle', defaultQty: 1 },
  { name: 'Canoness', faction: 'Adepta Sororitas', unitType: 'Character', defaultQty: 1 },
  { name: 'Custodian Guard', faction: 'Adeptus Custodes', unitType: 'Troops', defaultQty: 5 },
  { name: 'Allarus Terminators', faction: 'Adeptus Custodes', unitType: 'Infantry', defaultQty: 3 },
  { name: 'Vertus Praetors', faction: 'Adeptus Custodes', unitType: 'Mounted', defaultQty: 3 },
  { name: 'Grey Knights Strike Squad', faction: 'Grey Knights', unitType: 'Troops', defaultQty: 5 },
  { name: 'Grey Knights Terminators', faction: 'Grey Knights', unitType: 'Infantry', defaultQty: 5 },
  { name: 'Skitarii Rangers', faction: 'Adeptus Mechanicus', unitType: 'Troops', defaultQty: 10 },
  { name: 'Skitarii Vanguard', faction: 'Adeptus Mechanicus', unitType: 'Troops', defaultQty: 10 },
  { name: 'Onager Dunecrawler', faction: 'Adeptus Mechanicus', unitType: 'Vehicle', defaultQty: 1 },
  { name: 'Kastelan Robots', faction: 'Adeptus Mechanicus', unitType: 'Vehicle', defaultQty: 2 },
  { name: 'Ironstrider Ballistarius', faction: 'Adeptus Mechanicus', unitType: 'Walker', defaultQty: 1 },
  { name: 'Sydonian Dragoons', faction: 'Adeptus Mechanicus', unitType: 'Walker', defaultQty: 1 },
  { name: 'Pteraxii Sterylizors', faction: 'Adeptus Mechanicus', unitType: 'Jump Infantry', defaultQty: 5 },
  { name: 'Pteraxii Skystalkers', faction: 'Adeptus Mechanicus', unitType: 'Jump Infantry', defaultQty: 5 },
  { name: 'Sicarian Infiltrators', faction: 'Adeptus Mechanicus', unitType: 'Infantry', defaultQty: 5 },
  { name: 'Sicarian Ruststalkers', faction: 'Adeptus Mechanicus', unitType: 'Infantry', defaultQty: 5 },
  { name: 'Kataphron Breachers', faction: 'Adeptus Mechanicus', unitType: 'Infantry', defaultQty: 3 },
  { name: 'Kataphron Destroyers', faction: 'Adeptus Mechanicus', unitType: 'Infantry', defaultQty: 3 },
  { name: 'Archaeopter', faction: 'Adeptus Mechanicus', unitType: 'Vehicle', defaultQty: 1 },
  { name: 'Tech-Priest Dominus', faction: 'Adeptus Mechanicus', unitType: 'Character', defaultQty: 1 },
  { name: 'Tech-Priest Manipulus', faction: 'Adeptus Mechanicus', unitType: 'Character', defaultQty: 1 },
  { name: 'Belisarius Cawl', faction: 'Adeptus Mechanicus', unitType: 'Character', defaultQty: 1 },
  { name: 'Knight Paladin', faction: 'Imperial Knights', unitType: 'Titanic', defaultQty: 1 },
  { name: 'Knight Errant', faction: 'Imperial Knights', unitType: 'Titanic', defaultQty: 1 },
  { name: 'Knight Crusader', faction: 'Imperial Knights', unitType: 'Titanic', defaultQty: 1 },
  { name: 'Knight Gallant', faction: 'Imperial Knights', unitType: 'Titanic', defaultQty: 1 },
  { name: 'Knight Warden', faction: 'Imperial Knights', unitType: 'Titanic', defaultQty: 1 },
  { name: 'Knight Castellan', faction: 'Imperial Knights', unitType: 'Titanic', defaultQty: 1 },
  { name: 'Knight Valiant', faction: 'Imperial Knights', unitType: 'Titanic', defaultQty: 1 },
  { name: 'Armiger Warglaive', faction: 'Imperial Knights', unitType: 'Vehicle', defaultQty: 1 },
  { name: 'Armiger Helverin', faction: 'Imperial Knights', unitType: 'Vehicle', defaultQty: 1 },
  { name: 'Canis Rex', faction: 'Imperial Knights', unitType: 'Character', defaultQty: 1 },
  { name: 'War Dog Stalker', faction: 'Chaos Knights', unitType: 'Vehicle', defaultQty: 1 },
  { name: 'War Dog Karnivore', faction: 'Chaos Knights', unitType: 'Vehicle', defaultQty: 1 },
  { name: 'War Dog Executioner', faction: 'Chaos Knights', unitType: 'Vehicle', defaultQty: 1 },
  { name: 'Knight Desecrator', faction: 'Chaos Knights', unitType: 'Titanic', defaultQty: 1 },
  { name: 'Knight Rampager', faction: 'Chaos Knights', unitType: 'Titanic', defaultQty: 1 },
  { name: 'Knight Abominant', faction: 'Chaos Knights', unitType: 'Titanic', defaultQty: 1 },
  { name: 'Knight Despoiler', faction: 'Chaos Knights', unitType: 'Titanic', defaultQty: 1 },
  { name: 'Vindicare Assassin', faction: 'Agents of the Imperium', unitType: 'Character', defaultQty: 1 },
  { name: 'Eversor Assassin', faction: 'Agents of the Imperium', unitType: 'Character', defaultQty: 1 },
  { name: 'Callidus Assassin', faction: 'Agents of the Imperium', unitType: 'Character', defaultQty: 1 },
  { name: 'Culexus Assassin', faction: 'Agents of the Imperium', unitType: 'Character', defaultQty: 1 },
  { name: 'Inquisitor', faction: 'Agents of the Imperium', unitType: 'Character', defaultQty: 1 },
  { name: 'Deathwatch Veterans', faction: 'Space Marines', unitType: 'Infantry', defaultQty: 5 },
  { name: 'Vanguard Veterans', faction: 'Space Marines', unitType: 'Jump Infantry', defaultQty: 5 },
  { name: 'Centurion Devastators', faction: 'Space Marines', unitType: 'Infantry', defaultQty: 3 },
  { name: 'Devastator Squad', faction: 'Space Marines', unitType: 'Infantry', defaultQty: 5 },
  { name: 'Sanguinary Guard', faction: 'Space Marines', unitType: 'Jump Infantry', defaultQty: 5 },
  { name: 'Death Company Intercessors', faction: 'Space Marines', unitType: 'Infantry', defaultQty: 5 },
  { name: 'Death Company Marines', faction: 'Space Marines', unitType: 'Infantry', defaultQty: 5 },
  { name: 'Wulfen', faction: 'Space Marines', unitType: 'Infantry', defaultQty: 5 },
  { name: 'Thunderwolf Cavalry', faction: 'Space Marines', unitType: 'Mounted', defaultQty: 3 },
  { name: 'Long Fangs', faction: 'Space Marines', unitType: 'Infantry', defaultQty: 5 },
  { name: 'Deathwing Knights', faction: 'Space Marines', unitType: 'Infantry', defaultQty: 5 },
  { name: 'Ravenwing Black Knights', faction: 'Space Marines', unitType: 'Mounted', defaultQty: 3 },
  { name: 'Ravenwing Dark Talon', faction: 'Space Marines', unitType: 'Vehicle', defaultQty: 1 },
  { name: 'Drop Pod', faction: 'Space Marines', unitType: 'Vehicle', defaultQty: 1 },
  { name: 'Razorback', faction: 'Space Marines', unitType: 'Vehicle', defaultQty: 1 },
  { name: 'Rhino', faction: 'Space Marines', unitType: 'Vehicle', defaultQty: 1 },
  { name: 'Predator', faction: 'Space Marines', unitType: 'Vehicle', defaultQty: 1 },
  { name: 'Vindicator', faction: 'Space Marines', unitType: 'Vehicle', defaultQty: 1 },
  { name: 'Whirlwind', faction: 'Space Marines', unitType: 'Vehicle', defaultQty: 1 },
  { name: 'Stormhawk Interceptor', faction: 'Space Marines', unitType: 'Vehicle', defaultQty: 1 },
  { name: 'Techmarine', faction: 'Space Marines', unitType: 'Character', defaultQty: 1 },
  { name: 'Primaris Captain', faction: 'Space Marines', unitType: 'Character', defaultQty: 1 },
  { name: 'Primaris Chaplain', faction: 'Space Marines', unitType: 'Character', defaultQty: 1 },
  { name: 'Primaris Librarian', faction: 'Space Marines', unitType: 'Character', defaultQty: 1 },
  { name: 'Chapter Master', faction: 'Space Marines', unitType: 'Character', defaultQty: 1 },
  { name: 'Biologis Putrifier', faction: 'Death Guard', unitType: 'Character', defaultQty: 1 },
  { name: 'Foul Blightspawn', faction: 'Death Guard', unitType: 'Character', defaultQty: 1 },
  { name: 'Tallyman', faction: 'Death Guard', unitType: 'Character', defaultQty: 1 },
  { name: 'Deathshroud Terminators', faction: 'Death Guard', unitType: 'Infantry', defaultQty: 3 },
  { name: 'Myphitic Blight-Hauler', faction: 'Death Guard', unitType: 'Vehicle', defaultQty: 1 },
  { name: 'Foetid Bloat-drone', faction: 'Death Guard', unitType: 'Vehicle', defaultQty: 1 },
  { name: 'Mortarion', faction: 'Death Guard', unitType: 'Character', defaultQty: 1 },
  { name: 'Ahriman', faction: 'Thousand Sons', unitType: 'Character', defaultQty: 1 },
  { name: 'Infernal Master', faction: 'Thousand Sons', unitType: 'Character', defaultQty: 1 },
  { name: 'Exalted Sorcerer', faction: 'Thousand Sons', unitType: 'Character', defaultQty: 1 },
  { name: 'Mutalith Vortex Beast', faction: 'Thousand Sons', unitType: 'Monster', defaultQty: 1 },
  { name: 'Angron', faction: 'World Eaters', unitType: 'Character', defaultQty: 1 },
  { name: 'Lord Invocatus', faction: 'World Eaters', unitType: 'Character', defaultQty: 1 },
  { name: 'Exalted Eightbound', faction: 'World Eaters', unitType: 'Infantry', defaultQty: 3 },
  { name: 'Abaddon the Despoiler', faction: 'Chaos Space Marines', unitType: 'Character', defaultQty: 1 },
  { name: 'Venomcrawler', faction: 'Chaos Space Marines', unitType: 'Vehicle', defaultQty: 1 },
  { name: 'Defiler', faction: 'Chaos Space Marines', unitType: 'Vehicle', defaultQty: 1 },
  { name: 'Land Raider', faction: 'Chaos Space Marines', unitType: 'Vehicle', defaultQty: 1 },
  { name: 'Chaos Rhino', faction: 'Chaos Space Marines', unitType: 'Vehicle', defaultQty: 1 },
  { name: 'Chaos Terminators', faction: 'Chaos Space Marines', unitType: 'Infantry', defaultQty: 5 },
  { name: 'Warp Talons', faction: 'Chaos Space Marines', unitType: 'Jump Infantry', defaultQty: 5 },
  { name: 'Raptors', faction: 'Chaos Space Marines', unitType: 'Jump Infantry', defaultQty: 5 },
  { name: 'Noise Marines', faction: 'Chaos Space Marines', unitType: 'Infantry', defaultQty: 5 },
  { name: 'Sorcerer', faction: 'Chaos Space Marines', unitType: 'Character', defaultQty: 1 },
  { name: 'Keeper of Secrets', faction: 'Chaos Daemons', unitType: 'Monster', defaultQty: 1 },
  { name: 'Great Unclean One', faction: 'Chaos Daemons', unitType: 'Monster', defaultQty: 1 },
  { name: 'Lord of Change', faction: 'Chaos Daemons', unitType: 'Monster', defaultQty: 1 },
  { name: 'Bloodthirster', faction: 'Chaos Daemons', unitType: 'Monster', defaultQty: 1 },
  { name: 'Flamers of Tzeentch', faction: 'Chaos Daemons', unitType: 'Infantry', defaultQty: 3 },
  { name: 'Nurglings', faction: 'Chaos Daemons', unitType: 'Swarm', defaultQty: 3 },
  { name: 'Seekers of Slaanesh', faction: 'Chaos Daemons', unitType: 'Mounted', defaultQty: 5 },
  { name: 'Flesh Hounds', faction: 'Chaos Daemons', unitType: 'Beasts', defaultQty: 5 },
  { name: 'Skull Cannon', faction: 'Chaos Daemons', unitType: 'Vehicle', defaultQty: 1 },
  { name: 'Soul Grinder', faction: 'Chaos Daemons', unitType: 'Vehicle', defaultQty: 1 },
  { name: 'Screamers of Tzeentch', faction: 'Chaos Daemons', unitType: 'Beasts', defaultQty: 3 },
  { name: 'Beasts of Nurgle', faction: 'Chaos Daemons', unitType: 'Beasts', defaultQty: 1 },
  { name: 'Shield-Captain', faction: 'Adeptus Custodes', unitType: 'Character', defaultQty: 1 },
  { name: 'Blade Champion', faction: 'Adeptus Custodes', unitType: 'Character', defaultQty: 1 },
  { name: 'Wardens', faction: 'Adeptus Custodes', unitType: 'Infantry', defaultQty: 4 },
  { name: 'Prosecutors', faction: 'Adeptus Custodes', unitType: 'Troops', defaultQty: 5 },
  { name: 'Vigilators', faction: 'Adeptus Custodes', unitType: 'Infantry', defaultQty: 5 },
  { name: 'Witchseekers', faction: 'Adeptus Custodes', unitType: 'Infantry', defaultQty: 5 },
  { name: 'Caladius Grav-tank', faction: 'Adeptus Custodes', unitType: 'Vehicle', defaultQty: 1 },
  { name: 'Venerable Land Raider', faction: 'Adeptus Custodes', unitType: 'Vehicle', defaultQty: 1 },
  { name: 'Trajann Valoris', faction: 'Adeptus Custodes', unitType: 'Character', defaultQty: 1 },
  { name: 'Grey Knights Paladins', faction: 'Grey Knights', unitType: 'Infantry', defaultQty: 5 },
  { name: 'Grey Knights Purifiers', faction: 'Grey Knights', unitType: 'Infantry', defaultQty: 5 },
  { name: 'Grey Knights Interceptors', faction: 'Grey Knights', unitType: 'Jump Infantry', defaultQty: 5 },
  { name: 'Grey Knights Purgation Squad', faction: 'Grey Knights', unitType: 'Infantry', defaultQty: 5 },
  { name: 'Nemesis Dreadknight', faction: 'Grey Knights', unitType: 'Vehicle', defaultQty: 1 },
  { name: 'Grand Master', faction: 'Grey Knights', unitType: 'Character', defaultQty: 1 },
  { name: 'Librarian', faction: 'Grey Knights', unitType: 'Character', defaultQty: 1 },
  { name: 'Kaldor Draigo', faction: 'Grey Knights', unitType: 'Character', defaultQty: 1 },
  { name: 'Celestian Sacresants', faction: 'Adepta Sororitas', unitType: 'Infantry', defaultQty: 5 },
  { name: 'Zephyrim', faction: 'Adepta Sororitas', unitType: 'Jump Infantry', defaultQty: 5 },
  { name: 'Dominions', faction: 'Adepta Sororitas', unitType: 'Infantry', defaultQty: 5 },
  { name: 'Paragon Warsuits', faction: 'Adepta Sororitas', unitType: 'Vehicle', defaultQty: 3 },
  { name: 'Immolator', faction: 'Adepta Sororitas', unitType: 'Vehicle', defaultQty: 1 },
  { name: 'Castigator', faction: 'Adepta Sororitas', unitType: 'Vehicle', defaultQty: 1 },
  { name: 'Penitent Engine', faction: 'Adepta Sororitas', unitType: 'Vehicle', defaultQty: 1 },
  { name: 'Morvenn Vahl', faction: 'Adepta Sororitas', unitType: 'Character', defaultQty: 1 },
  { name: 'Palatine', faction: 'Adepta Sororitas', unitType: 'Character', defaultQty: 1 },
  { name: 'Dialogus', faction: 'Adepta Sororitas', unitType: 'Character', defaultQty: 1 },
  { name: 'Hospitaller', faction: 'Adepta Sororitas', unitType: 'Character', defaultQty: 1 },
  { name: 'Infantry Squad', faction: 'Astra Militarum', unitType: 'Troops', defaultQty: 10 },
  { name: 'Tempestus Scions', faction: 'Astra Militarum', unitType: 'Infantry', defaultQty: 5 },
  { name: 'Catachan Jungle Fighters', faction: 'Astra Militarum', unitType: 'Troops', defaultQty: 10 },
  { name: 'Bullgryns', faction: 'Astra Militarum', unitType: 'Infantry', defaultQty: 3 },
  { name: 'Ratlings', faction: 'Astra Militarum', unitType: 'Infantry', defaultQty: 5 },
  { name: 'Basilisk', faction: 'Astra Militarum', unitType: 'Vehicle', defaultQty: 1 },
  { name: 'Manticore', faction: 'Astra Militarum', unitType: 'Vehicle', defaultQty: 1 },
  { name: 'Hellhound', faction: 'Astra Militarum', unitType: 'Vehicle', defaultQty: 1 },
  { name: 'Valkyrie', faction: 'Astra Militarum', unitType: 'Vehicle', defaultQty: 1 },
  { name: 'Hydra', faction: 'Astra Militarum', unitType: 'Vehicle', defaultQty: 1 },
  { name: 'Deathstrike', faction: 'Astra Militarum', unitType: 'Vehicle', defaultQty: 1 },
  { name: 'Tank Commander', faction: 'Astra Militarum', unitType: 'Character', defaultQty: 1 },
  { name: 'Commissar', faction: 'Astra Militarum', unitType: 'Character', defaultQty: 1 },
  { name: 'Platoon Command Squad', faction: 'Astra Militarum', unitType: 'Character', defaultQty: 5 },
];

const chaos: ModelPreset[] = [
  { name: 'Legionaries', faction: 'Chaos Space Marines', unitType: 'Troops', defaultQty: 10 },
  { name: 'Chosen', faction: 'Chaos Space Marines', unitType: 'Infantry', defaultQty: 5 },
  { name: 'Possessed', faction: 'Chaos Space Marines', unitType: 'Infantry', defaultQty: 5 },
  { name: 'Havocs', faction: 'Chaos Space Marines', unitType: 'Infantry', defaultQty: 5 },
  { name: 'Obliterators', faction: 'Chaos Space Marines', unitType: 'Infantry', defaultQty: 2 },
  { name: 'Helbrute', faction: 'Chaos Space Marines', unitType: 'Vehicle', defaultQty: 1 },
  { name: 'Forgefiend', faction: 'Chaos Space Marines', unitType: 'Vehicle', defaultQty: 1 },
  { name: 'Maulerfiend', faction: 'Chaos Space Marines', unitType: 'Vehicle', defaultQty: 1 },
  { name: 'Chaos Lord', faction: 'Chaos Space Marines', unitType: 'Character', defaultQty: 1 },
  { name: 'Dark Apostle', faction: 'Chaos Space Marines', unitType: 'Character', defaultQty: 1 },
  { name: 'Master of Possession', faction: 'Chaos Space Marines', unitType: 'Character', defaultQty: 1 },
  { name: 'Accursed Cultists', faction: 'Chaos Space Marines', unitType: 'Troops', defaultQty: 8 },
  { name: 'Plague Marines', faction: 'Death Guard', unitType: 'Troops', defaultQty: 7 },
  { name: 'Poxwalkers', faction: 'Death Guard', unitType: 'Troops', defaultQty: 10 },
  { name: 'Blightlord Terminators', faction: 'Death Guard', unitType: 'Infantry', defaultQty: 5 },
  { name: 'Plagueburst Crawler', faction: 'Death Guard', unitType: 'Vehicle', defaultQty: 1 },
  { name: 'Lord of Contagion', faction: 'Death Guard', unitType: 'Character', defaultQty: 1 },
  { name: 'Rubric Marines', faction: 'Thousand Sons', unitType: 'Troops', defaultQty: 10 },
  { name: 'Scarab Occult Terminators', faction: 'Thousand Sons', unitType: 'Infantry', defaultQty: 5 },
  { name: 'Tzaangors', faction: 'Thousand Sons', unitType: 'Troops', defaultQty: 10 },
  { name: 'Berzerkers', faction: 'World Eaters', unitType: 'Troops', defaultQty: 10 },
  { name: 'Jakhals', faction: 'World Eaters', unitType: 'Troops', defaultQty: 10 },
  { name: 'Eightbound', faction: 'World Eaters', unitType: 'Infantry', defaultQty: 3 },
  { name: 'Bloodletters', faction: 'Chaos Daemons', unitType: 'Troops', defaultQty: 10 },
  { name: 'Plaguebearers', faction: 'Chaos Daemons', unitType: 'Troops', defaultQty: 10 },
  { name: 'Daemonettes', faction: 'Chaos Daemons', unitType: 'Troops', defaultQty: 10 },
  { name: 'Pink Horrors', faction: 'Chaos Daemons', unitType: 'Troops', defaultQty: 10 },
];

const xenos: ModelPreset[] = [
  { name: 'Boyz', faction: 'Orks', unitType: 'Troops', defaultQty: 10 },
  { name: 'Gretchin', faction: 'Orks', unitType: 'Troops', defaultQty: 10 },
  { name: 'Nobz', faction: 'Orks', unitType: 'Infantry', defaultQty: 5 },
  { name: 'Meganobz', faction: 'Orks', unitType: 'Infantry', defaultQty: 3 },
  { name: 'Lootas', faction: 'Orks', unitType: 'Infantry', defaultQty: 5 },
  { name: 'Deff Dread', faction: 'Orks', unitType: 'Vehicle', defaultQty: 1 },
  { name: 'Trukk', faction: 'Orks', unitType: 'Vehicle', defaultQty: 1 },
  { name: 'Warboss', faction: 'Orks', unitType: 'Character', defaultQty: 1 },
  { name: 'Kill Rig', faction: 'Orks', unitType: 'Vehicle', defaultQty: 1 },
  { name: 'Fire Warriors', faction: 'Tau Empire', unitType: 'Troops', defaultQty: 10 },
  { name: 'Pathfinders', faction: 'Tau Empire', unitType: 'Infantry', defaultQty: 10 },
  { name: 'Crisis Battlesuits', faction: 'Tau Empire', unitType: 'Battlesuits', defaultQty: 3 },
  { name: 'Broadside Battlesuit', faction: 'Tau Empire', unitType: 'Battlesuits', defaultQty: 1 },
  { name: 'Riptide Battlesuit', faction: 'Tau Empire', unitType: 'Battlesuits', defaultQty: 1 },
  { name: 'Hammerhead', faction: 'Tau Empire', unitType: 'Vehicle', defaultQty: 1 },
  { name: 'Devilfish', faction: 'Tau Empire', unitType: 'Vehicle', defaultQty: 1 },
  { name: 'Commander', faction: 'Tau Empire', unitType: 'Character', defaultQty: 1 },
  { name: 'Termagants', faction: 'Tyranids', unitType: 'Troops', defaultQty: 10 },
  { name: 'Hormagaunts', faction: 'Tyranids', unitType: 'Troops', defaultQty: 10 },
  { name: 'Genestealers', faction: 'Tyranids', unitType: 'Infantry', defaultQty: 5 },
  { name: 'Warriors', faction: 'Tyranids', unitType: 'Infantry', defaultQty: 3 },
  { name: 'Carnifex', faction: 'Tyranids', unitType: 'Monster', defaultQty: 1 },
  { name: 'Hive Tyrant', faction: 'Tyranids', unitType: 'Character', defaultQty: 1 },
  { name: 'Screamer-Killer', faction: 'Tyranids', unitType: 'Monster', defaultQty: 1 },
  { name: 'Zoanthropes', faction: 'Tyranids', unitType: 'Infantry', defaultQty: 3 },
  { name: 'Necron Warriors', faction: 'Necrons', unitType: 'Troops', defaultQty: 10 },
  { name: 'Immortals', faction: 'Necrons', unitType: 'Troops', defaultQty: 5 },
  { name: 'Lychguard', faction: 'Necrons', unitType: 'Infantry', defaultQty: 5 },
  { name: 'Skorpekh Destroyers', faction: 'Necrons', unitType: 'Infantry', defaultQty: 3 },
  { name: 'Lokhust Heavy Destroyers', faction: 'Necrons', unitType: 'Infantry', defaultQty: 1 },
  { name: 'Canoptek Wraiths', faction: 'Necrons', unitType: 'Beasts', defaultQty: 3 },
  { name: 'Doomsday Ark', faction: 'Necrons', unitType: 'Vehicle', defaultQty: 1 },
  { name: 'Ghost Ark', faction: 'Necrons', unitType: 'Vehicle', defaultQty: 1 },
  { name: 'Overlord', faction: 'Necrons', unitType: 'Character', defaultQty: 1 },
  { name: 'Guardians', faction: 'Aeldari', unitType: 'Troops', defaultQty: 10 },
  { name: 'Dire Avengers', faction: 'Aeldari', unitType: 'Troops', defaultQty: 5 },
  { name: 'Howling Banshees', faction: 'Aeldari', unitType: 'Infantry', defaultQty: 5 },
  { name: 'Fire Dragons', faction: 'Aeldari', unitType: 'Infantry', defaultQty: 5 },
  { name: 'Wraithguard', faction: 'Aeldari', unitType: 'Infantry', defaultQty: 5 },
  { name: 'Wraithlord', faction: 'Aeldari', unitType: 'Monster', defaultQty: 1 },
  { name: 'Wave Serpent', faction: 'Aeldari', unitType: 'Vehicle', defaultQty: 1 },
  { name: 'War Walker', faction: 'Aeldari', unitType: 'Walker', defaultQty: 1 },
  { name: 'Farseer', faction: 'Aeldari', unitType: 'Character', defaultQty: 1 },
  { name: 'Kabalite Warriors', faction: 'Drukhari', unitType: 'Troops', defaultQty: 10 },
  { name: 'Wyches', faction: 'Drukhari', unitType: 'Troops', defaultQty: 10 },
  { name: 'Incubi', faction: 'Drukhari', unitType: 'Infantry', defaultQty: 5 },
  { name: 'Raider', faction: 'Drukhari', unitType: 'Vehicle', defaultQty: 1 },
  { name: 'Neophyte Hybrids', faction: 'Genestealer Cults', unitType: 'Troops', defaultQty: 10 },
  { name: 'Acolyte Hybrids', faction: 'Genestealer Cults', unitType: 'Troops', defaultQty: 5 },
  { name: 'Leagues Hearthkyn Warriors', faction: 'Leagues of Votann', unitType: 'Troops', defaultQty: 10 },
  { name: 'Einhyr Hearthguard', faction: 'Leagues of Votann', unitType: 'Infantry', defaultQty: 5 },
  { name: 'Sagitaur', faction: 'Leagues of Votann', unitType: 'Vehicle', defaultQty: 1 },
  { name: 'Kahl', faction: 'Leagues of Votann', unitType: 'Character', defaultQty: 1 },
  { name: 'Ranger Squad', faction: 'Aeldari', unitType: 'Troops', defaultQty: 5 },
  { name: 'Striking Scorpions', faction: 'Aeldari', unitType: 'Infantry', defaultQty: 5 },
  { name: 'Dark Reapers', faction: 'Aeldari', unitType: 'Infantry', defaultQty: 5 },
  { name: 'Warp Spiders', faction: 'Aeldari', unitType: 'Infantry', defaultQty: 5 },
  { name: 'Swooping Hawks', faction: 'Aeldari', unitType: 'Jump Infantry', defaultQty: 5 },
  { name: 'Shining Spears', faction: 'Aeldari', unitType: 'Mounted', defaultQty: 3 },
  { name: 'Falcon', faction: 'Aeldari', unitType: 'Vehicle', defaultQty: 1 },
  { name: 'Fire Prism', faction: 'Aeldari', unitType: 'Vehicle', defaultQty: 1 },
  { name: 'Night Spinner', faction: 'Aeldari', unitType: 'Vehicle', defaultQty: 1 },
  { name: 'Wraithknight', faction: 'Aeldari', unitType: 'Monster', defaultQty: 1 },
  { name: 'Avatar of Khaine', faction: 'Aeldari', unitType: 'Character', defaultQty: 1 },
  { name: 'Warlock', faction: 'Aeldari', unitType: 'Character', defaultQty: 1 },
  { name: 'Autarch', faction: 'Aeldari', unitType: 'Character', defaultQty: 1 },
  { name: 'Venom', faction: 'Drukhari', unitType: 'Vehicle', defaultQty: 1 },
  { name: 'Ravager', faction: 'Drukhari', unitType: 'Vehicle', defaultQty: 1 },
  { name: 'Mandrakes', faction: 'Drukhari', unitType: 'Infantry', defaultQty: 5 },
  { name: 'Hellions', faction: 'Drukhari', unitType: 'Jump Infantry', defaultQty: 5 },
  { name: 'Archon', faction: 'Drukhari', unitType: 'Character', defaultQty: 1 },
  { name: 'Winged Tyrant', faction: 'Tyranids', unitType: 'Character', defaultQty: 1 },
  { name: 'Tyrannofex', faction: 'Tyranids', unitType: 'Monster', defaultQty: 1 },
  { name: 'Exocrine', faction: 'Tyranids', unitType: 'Monster', defaultQty: 1 },
  { name: 'Haruspex', faction: 'Tyranids', unitType: 'Monster', defaultQty: 1 },
  { name: 'Lictor', faction: 'Tyranids', unitType: 'Infantry', defaultQty: 1 },
  { name: 'Von Ryan Leapers', faction: 'Tyranids', unitType: 'Infantry', defaultQty: 3 },
  { name: 'Gargoyles', faction: 'Tyranids', unitType: 'Jump Infantry', defaultQty: 10 },
  { name: 'Ripper Swarms', faction: 'Tyranids', unitType: 'Swarm', defaultQty: 3 },
  { name: 'Biovore', faction: 'Tyranids', unitType: 'Infantry', defaultQty: 1 },
  { name: 'Psychophage', faction: 'Tyranids', unitType: 'Monster', defaultQty: 1 },
  { name: 'Neurogaunts', faction: 'Tyranids', unitType: 'Troops', defaultQty: 11 },
  { name: 'Barbgaunts', faction: 'Tyranids', unitType: 'Infantry', defaultQty: 5 },
  { name: 'Canoptek Scarab Swarms', faction: 'Necrons', unitType: 'Swarm', defaultQty: 3 },
  { name: 'Canoptek Spyder', faction: 'Necrons', unitType: 'Vehicle', defaultQty: 1 },
  { name: 'Triarch Praetorians', faction: 'Necrons', unitType: 'Infantry', defaultQty: 5 },
  { name: 'Deathmarks', faction: 'Necrons', unitType: 'Infantry', defaultQty: 5 },
  { name: 'Flayed Ones', faction: 'Necrons', unitType: 'Infantry', defaultQty: 5 },
  { name: 'Ophydian Destroyers', faction: 'Necrons', unitType: 'Infantry', defaultQty: 3 },
  { name: 'Annihilation Barge', faction: 'Necrons', unitType: 'Vehicle', defaultQty: 1 },
  { name: 'Monolith', faction: 'Necrons', unitType: 'Vehicle', defaultQty: 1 },
  { name: 'C\'tan Shard', faction: 'Necrons', unitType: 'Character', defaultQty: 1 },
  { name: 'Cryptek', faction: 'Necrons', unitType: 'Character', defaultQty: 1 },
  { name: 'Stormboyz', faction: 'Orks', unitType: 'Jump Infantry', defaultQty: 5 },
  { name: 'Kommandos', faction: 'Orks', unitType: 'Infantry', defaultQty: 10 },
  { name: 'Burna Boyz', faction: 'Orks', unitType: 'Infantry', defaultQty: 5 },
  { name: 'Flash Gitz', faction: 'Orks', unitType: 'Infantry', defaultQty: 5 },
  { name: 'Killa Kans', faction: 'Orks', unitType: 'Walker', defaultQty: 3 },
  { name: 'Gorkanaut', faction: 'Orks', unitType: 'Vehicle', defaultQty: 1 },
  { name: 'Battlewagon', faction: 'Orks', unitType: 'Vehicle', defaultQty: 1 },
  { name: 'Weirdboy', faction: 'Orks', unitType: 'Character', defaultQty: 1 },
  { name: 'Big Mek', faction: 'Orks', unitType: 'Character', defaultQty: 1 },
  { name: 'Stealth Battlesuits', faction: 'Tau Empire', unitType: 'Battlesuits', defaultQty: 3 },
  { name: 'Ghostkeel Battlesuit', faction: 'Tau Empire', unitType: 'Battlesuits', defaultQty: 1 },
  { name: 'Stormsurge', faction: 'Tau Empire', unitType: 'Battlesuits', defaultQty: 1 },
  { name: 'Kroot Carnivores', faction: 'Tau Empire', unitType: 'Troops', defaultQty: 10 },
  { name: 'Kroot Farstalkers', faction: 'Tau Empire', unitType: 'Infantry', defaultQty: 10 },
  { name: 'Ethereal', faction: 'Tau Empire', unitType: 'Character', defaultQty: 1 },
  { name: 'Cadre Fireblade', faction: 'Tau Empire', unitType: 'Character', defaultQty: 1 },
  { name: 'Aberrants', faction: 'Genestealer Cults', unitType: 'Infantry', defaultQty: 5 },
  { name: 'Ridgerunner', faction: 'Genestealer Cults', unitType: 'Vehicle', defaultQty: 1 },
  { name: 'Goliath Truck', faction: 'Genestealer Cults', unitType: 'Vehicle', defaultQty: 1 },
  { name: 'Patriarch', faction: 'Genestealer Cults', unitType: 'Character', defaultQty: 1 },
];

import { KILLTEAM_PRESETS } from './model-presets-extra';
import { MORE_MODELS } from './model-presets-more';
import { KILLTEAM_OPERATIVES } from './model-presets-killteam-ops';
import { COMBAT_PATROLS } from './model-presets-combat-patrol';
import { MORE_40K } from './model-presets-40k-more';
import { LATEST_MODELS } from './model-presets-latest';
import { PRIMARCH_MODELS } from './primarchs-and-sp1';

export const ALL_MODEL_PRESETS: ModelPreset[] = [...imperium, ...chaos, ...xenos, ...KILLTEAM_PRESETS, ...MORE_MODELS, ...KILLTEAM_OPERATIVES, ...COMBAT_PATROLS, ...MORE_40K, ...LATEST_MODELS, ...PRIMARCH_MODELS];
