import type { ModelPreset } from './model-presets';

export const MORE_MODELS: ModelPreset[] = [
  // ─── Aeldari ───
  { name: 'Windriders', faction: 'Aeldari', unitType: 'Mounted', defaultQty: 3 },
  { name: 'Vyper', faction: 'Aeldari', unitType: 'Vehicle', defaultQty: 1 },
  { name: 'Crimson Hunter', faction: 'Aeldari', unitType: 'Vehicle', defaultQty: 1 },
  { name: 'Hemlock Wraithfighter', faction: 'Aeldari', unitType: 'Vehicle', defaultQty: 1 },
  { name: 'Wraithseer', faction: 'Aeldari', unitType: 'Monster', defaultQty: 1 },
  { name: 'Wraithblades', faction: 'Aeldari', unitType: 'Infantry', defaultQty: 5 },
  { name: 'Shadow Spectres', faction: 'Aeldari', unitType: 'Infantry', defaultQty: 5 },
  { name: 'Spiritseer', faction: 'Aeldari', unitType: 'Character', defaultQty: 1 },
  { name: 'Eldrad Ulthran', faction: 'Aeldari', unitType: 'Character', defaultQty: 1 },
  { name: 'Jain Zar', faction: 'Aeldari', unitType: 'Character', defaultQty: 1 },
  { name: 'Baharroth', faction: 'Aeldari', unitType: 'Character', defaultQty: 1 },
  { name: 'Fuegan', faction: 'Aeldari', unitType: 'Character', defaultQty: 1 },
  { name: 'Karandras', faction: 'Aeldari', unitType: 'Character', defaultQty: 1 },
  { name: 'Maugan Ra', faction: 'Aeldari', unitType: 'Character', defaultQty: 1 },
  { name: 'Yncarne', faction: 'Aeldari', unitType: 'Character', defaultQty: 1 },
  { name: 'Yvraine', faction: 'Aeldari', unitType: 'Character', defaultQty: 1 },
  { name: 'Visarch', faction: 'Aeldari', unitType: 'Character', defaultQty: 1 },
  { name: 'Support Weapons', faction: 'Aeldari', unitType: 'Vehicle', defaultQty: 1 },

  // ─── Drukhari ───
  { name: 'Scourges', faction: 'Drukhari', unitType: 'Jump Infantry', defaultQty: 5 },
  { name: 'Grotesques', faction: 'Drukhari', unitType: 'Infantry', defaultQty: 3 },
  { name: 'Wracks', faction: 'Drukhari', unitType: 'Infantry', defaultQty: 5 },
  { name: 'Reavers', faction: 'Drukhari', unitType: 'Mounted', defaultQty: 3 },
  { name: 'Talos', faction: 'Drukhari', unitType: 'Monster', defaultQty: 1 },
  { name: 'Cronos', faction: 'Drukhari', unitType: 'Monster', defaultQty: 1 },
  { name: 'Razorwing Jetfighter', faction: 'Drukhari', unitType: 'Vehicle', defaultQty: 1 },
  { name: 'Voidraven Bomber', faction: 'Drukhari', unitType: 'Vehicle', defaultQty: 1 },
  { name: 'Succubus', faction: 'Drukhari', unitType: 'Character', defaultQty: 1 },
  { name: 'Haemonculus', faction: 'Drukhari', unitType: 'Character', defaultQty: 1 },
  { name: 'Drazhar', faction: 'Drukhari', unitType: 'Character', defaultQty: 1 },
  { name: 'Lelith Hesperax', faction: 'Drukhari', unitType: 'Character', defaultQty: 1 },
  { name: 'Court of the Archon', faction: 'Drukhari', unitType: 'Infantry', defaultQty: 4 },

  // ─── Adeptus Mechanicus ───
  { name: 'Corpuscarii Electro-Priests', faction: 'Adeptus Mechanicus', unitType: 'Infantry', defaultQty: 5 },
  { name: 'Fulgurite Electro-Priests', faction: 'Adeptus Mechanicus', unitType: 'Infantry', defaultQty: 5 },
  { name: 'Serberys Raiders', faction: 'Adeptus Mechanicus', unitType: 'Mounted', defaultQty: 3 },
  { name: 'Serberys Sulphurhounds', faction: 'Adeptus Mechanicus', unitType: 'Mounted', defaultQty: 3 },
  { name: 'Skorpius Disintegrator', faction: 'Adeptus Mechanicus', unitType: 'Vehicle', defaultQty: 1 },
  { name: 'Skorpius Dunerider', faction: 'Adeptus Mechanicus', unitType: 'Vehicle', defaultQty: 1 },
  { name: 'Cybernetica Datasmith', faction: 'Adeptus Mechanicus', unitType: 'Character', defaultQty: 1 },
  { name: 'Skystalker Marshal', faction: 'Adeptus Mechanicus', unitType: 'Character', defaultQty: 1 },

  // ─── Adepta Sororitas ───
  { name: 'Sacresant Squad', faction: 'Adepta Sororitas', unitType: 'Infantry', defaultQty: 5 },
  { name: 'Arco-Flagellants', faction: 'Adepta Sororitas', unitType: 'Infantry', defaultQty: 10 },
  { name: 'Crusaders', faction: 'Adepta Sororitas', unitType: 'Infantry', defaultQty: 4 },
  { name: 'Mortifiers', faction: 'Adepta Sororitas', unitType: 'Vehicle', defaultQty: 2 },
  { name: 'Rhino', faction: 'Adepta Sororitas', unitType: 'Vehicle', defaultQty: 1 },
  { name: 'Junith Eruita', faction: 'Adepta Sororitas', unitType: 'Character', defaultQty: 1 },
  { name: 'Ephrael Stern', faction: 'Adepta Sororitas', unitType: 'Character', defaultQty: 1 },
  { name: 'Aestred Thurga', faction: 'Adepta Sororitas', unitType: 'Character', defaultQty: 1 },
  { name: 'Dogmata', faction: 'Adepta Sororitas', unitType: 'Character', defaultQty: 1 },
  { name: 'Imagifier', faction: 'Adepta Sororitas', unitType: 'Character', defaultQty: 1 },

  // ─── Adeptus Custodes ───
  { name: 'Custodian Wardens', faction: 'Adeptus Custodes', unitType: 'Infantry', defaultQty: 4 },
  { name: 'Sagittarum Guard', faction: 'Adeptus Custodes', unitType: 'Infantry', defaultQty: 5 },
  { name: 'Venetari', faction: 'Adeptus Custodes', unitType: 'Jump Infantry', defaultQty: 3 },
  { name: 'Telemon Dreadnought', faction: 'Adeptus Custodes', unitType: 'Vehicle', defaultQty: 1 },
  { name: 'Contemptor-Achillus', faction: 'Adeptus Custodes', unitType: 'Vehicle', defaultQty: 1 },
  { name: 'Pallas Grav-attack', faction: 'Adeptus Custodes', unitType: 'Vehicle', defaultQty: 1 },
  { name: 'Valerian', faction: 'Adeptus Custodes', unitType: 'Character', defaultQty: 1 },
  { name: 'Aleya', faction: 'Adeptus Custodes', unitType: 'Character', defaultQty: 1 },

  // ─── Grey Knights ───
  { name: 'Brotherhood Champion', faction: 'Grey Knights', unitType: 'Character', defaultQty: 1 },
  { name: 'Castellan Crowe', faction: 'Grey Knights', unitType: 'Character', defaultQty: 1 },
  { name: 'Voldus', faction: 'Grey Knights', unitType: 'Character', defaultQty: 1 },
  { name: 'Servitors', faction: 'Grey Knights', unitType: 'Infantry', defaultQty: 4 },
  { name: 'Venerable Dreadnought', faction: 'Grey Knights', unitType: 'Vehicle', defaultQty: 1 },
  { name: 'Stormraven Gunship', faction: 'Grey Knights', unitType: 'Vehicle', defaultQty: 1 },
  { name: 'Land Raider', faction: 'Grey Knights', unitType: 'Vehicle', defaultQty: 1 },
  { name: 'Razorback', faction: 'Grey Knights', unitType: 'Vehicle', defaultQty: 1 },

  // ─── Death Guard ───
  { name: 'Noxious Blightbringer', faction: 'Death Guard', unitType: 'Character', defaultQty: 1 },
  { name: 'Plague Surgeon', faction: 'Death Guard', unitType: 'Character', defaultQty: 1 },
  { name: 'Lord of Virulence', faction: 'Death Guard', unitType: 'Character', defaultQty: 1 },
  { name: 'Typhus', faction: 'Death Guard', unitType: 'Character', defaultQty: 1 },
  { name: 'Blight-Hauler', faction: 'Death Guard', unitType: 'Vehicle', defaultQty: 1 },
  { name: 'Defiler', faction: 'Death Guard', unitType: 'Vehicle', defaultQty: 1 },
  { name: 'Rhino', faction: 'Death Guard', unitType: 'Vehicle', defaultQty: 1 },
  { name: 'Land Raider', faction: 'Death Guard', unitType: 'Vehicle', defaultQty: 1 },

  // ─── Thousand Sons ───
  { name: 'Exalted Sorcerers on Disc', faction: 'Thousand Sons', unitType: 'Character', defaultQty: 3 },
  { name: 'Tzaangor Shaman', faction: 'Thousand Sons', unitType: 'Character', defaultQty: 1 },
  { name: 'Tzaangor Enlightened', faction: 'Thousand Sons', unitType: 'Mounted', defaultQty: 3 },
  { name: 'Chaos Spawn', faction: 'Thousand Sons', unitType: 'Beasts', defaultQty: 2 },
  { name: 'Forgefiend', faction: 'Thousand Sons', unitType: 'Vehicle', defaultQty: 1 },
  { name: 'Heldrake', faction: 'Thousand Sons', unitType: 'Vehicle', defaultQty: 1 },
  { name: 'Rhino', faction: 'Thousand Sons', unitType: 'Vehicle', defaultQty: 1 },
  { name: 'Land Raider', faction: 'Thousand Sons', unitType: 'Vehicle', defaultQty: 1 },
  { name: 'Magnus the Red', faction: 'Thousand Sons', unitType: 'Character', defaultQty: 1 },

  // ─── World Eaters ───
  { name: 'World Eaters Master of Executions', faction: 'World Eaters', unitType: 'Character', defaultQty: 1 },
  { name: 'World Eaters Lord on Juggernaut', faction: 'World Eaters', unitType: 'Character', defaultQty: 1 },
  { name: 'Khorne Berzerkers', faction: 'World Eaters', unitType: 'Troops', defaultQty: 10 },
  { name: 'World Eaters Terminators', faction: 'World Eaters', unitType: 'Infantry', defaultQty: 5 },
  { name: 'Helbrute', faction: 'World Eaters', unitType: 'Vehicle', defaultQty: 1 },
  { name: 'Rhino', faction: 'World Eaters', unitType: 'Vehicle', defaultQty: 1 },
  { name: 'Land Raider', faction: 'World Eaters', unitType: 'Vehicle', defaultQty: 1 },
  { name: 'Defiler', faction: 'World Eaters', unitType: 'Vehicle', defaultQty: 1 },

  // ─── Genestealer Cults ───
  { name: 'Metamorphs', faction: 'Genestealer Cults', unitType: 'Infantry', defaultQty: 5 },
  { name: 'Purestrain Genestealers', faction: 'Genestealer Cults', unitType: 'Infantry', defaultQty: 5 },
  { name: 'Atalan Jackals', faction: 'Genestealer Cults', unitType: 'Mounted', defaultQty: 5 },
  { name: 'Achilles Ridgerunner', faction: 'Genestealer Cults', unitType: 'Vehicle', defaultQty: 1 },
  { name: 'Rockgrinder', faction: 'Genestealer Cults', unitType: 'Vehicle', defaultQty: 1 },
  { name: 'Sanctus', faction: 'Genestealer Cults', unitType: 'Character', defaultQty: 1 },
  { name: 'Primus', faction: 'Genestealer Cults', unitType: 'Character', defaultQty: 1 },
  { name: 'Magus', faction: 'Genestealer Cults', unitType: 'Character', defaultQty: 1 },
  { name: 'Kelermorph', faction: 'Genestealer Cults', unitType: 'Character', defaultQty: 1 },
  { name: 'Biophagus', faction: 'Genestealer Cults', unitType: 'Character', defaultQty: 1 },
  { name: 'Clamavus', faction: 'Genestealer Cults', unitType: 'Character', defaultQty: 1 },
  { name: 'Locus', faction: 'Genestealer Cults', unitType: 'Character', defaultQty: 1 },
  { name: 'Nexos', faction: 'Genestealer Cults', unitType: 'Character', defaultQty: 1 },

  // ─── Leagues of Votann ───
  { name: 'Cthonian Beserks', faction: 'Leagues of Votann', unitType: 'Infantry', defaultQty: 5 },
  { name: 'Hernkyn Pioneers', faction: 'Leagues of Votann', unitType: 'Mounted', defaultQty: 3 },
  { name: 'Hekaton Land Fortress', faction: 'Leagues of Votann', unitType: 'Vehicle', defaultQty: 1 },
  { name: 'Grimnyr', faction: 'Leagues of Votann', unitType: 'Character', defaultQty: 1 },
  { name: 'Brôkhyr Iron-master', faction: 'Leagues of Votann', unitType: 'Character', defaultQty: 1 },
  { name: 'Brôkhyr Thunderkyn', faction: 'Leagues of Votann', unitType: 'Infantry', defaultQty: 3 },
  { name: 'Uthar the Destined', faction: 'Leagues of Votann', unitType: 'Character', defaultQty: 1 },

  // ─── Agents of the Imperium ───
  { name: 'Rogue Trader Entourage', faction: 'Agents of the Imperium', unitType: 'Infantry', defaultQty: 4 },
  { name: 'Voidsmen-at-Arms', faction: 'Agents of the Imperium', unitType: 'Infantry', defaultQty: 5 },
  { name: 'Navigator', faction: 'Agents of the Imperium', unitType: 'Character', defaultQty: 1 },
  { name: 'Astropath', faction: 'Agents of the Imperium', unitType: 'Character', defaultQty: 1 },
  { name: 'Jokaero Weaponsmith', faction: 'Agents of the Imperium', unitType: 'Character', defaultQty: 1 },
  { name: 'Daemonhost', faction: 'Agents of the Imperium', unitType: 'Character', defaultQty: 1 },
  { name: 'Imperial Navy Breachers', faction: 'Agents of the Imperium', unitType: 'Kill Team', defaultQty: 10 },
  { name: 'Subductor Squad', faction: 'Agents of the Imperium', unitType: 'Infantry', defaultQty: 10 },

  // ─── Chaos Daemons ───
  { name: 'Fiends of Slaanesh', faction: 'Chaos Daemons', unitType: 'Beasts', defaultQty: 3 },
  { name: 'Exalted Flamer', faction: 'Chaos Daemons', unitType: 'Character', defaultQty: 1 },
  { name: 'Changeling', faction: 'Chaos Daemons', unitType: 'Character', defaultQty: 1 },
  { name: 'Blue Scribes', faction: 'Chaos Daemons', unitType: 'Character', defaultQty: 1 },
  { name: 'Epidemius', faction: 'Chaos Daemons', unitType: 'Character', defaultQty: 1 },
  { name: 'Spoilpox Scrivener', faction: 'Chaos Daemons', unitType: 'Character', defaultQty: 1 },
  { name: 'Sloppity Bilepiper', faction: 'Chaos Daemons', unitType: 'Character', defaultQty: 1 },
  { name: 'Infernal Enrapturess', faction: 'Chaos Daemons', unitType: 'Character', defaultQty: 1 },
  { name: 'Contorted Epitome', faction: 'Chaos Daemons', unitType: 'Character', defaultQty: 1 },
  { name: 'Karanak', faction: 'Chaos Daemons', unitType: 'Character', defaultQty: 1 },
  { name: 'Skulltaker', faction: 'Chaos Daemons', unitType: 'Character', defaultQty: 1 },
  { name: 'Skullmaster', faction: 'Chaos Daemons', unitType: 'Character', defaultQty: 1 },
  { name: 'Plague Drones', faction: 'Chaos Daemons', unitType: 'Mounted', defaultQty: 3 },
  { name: 'Burning Chariot', faction: 'Chaos Daemons', unitType: 'Vehicle', defaultQty: 1 },
  { name: 'Seeker Chariot', faction: 'Chaos Daemons', unitType: 'Vehicle', defaultQty: 1 },
  { name: 'Blood Throne', faction: 'Chaos Daemons', unitType: 'Vehicle', defaultQty: 1 },
  { name: 'Be\'lakor', faction: 'Chaos Daemons', unitType: 'Character', defaultQty: 1 },
];
