import type { PaintPreset } from './paints-citadel-base';

export const CITADEL_LAYER: PaintPreset[] = [
  { name: 'Administratum Grey', brand: 'Citadel', range: 'Layer', type: 'layer', hex: '#949b95' },
  { name: 'Alaitoc Blue', brand: 'Citadel', range: 'Layer', type: 'layer', hex: '#295788' },
  { name: 'Altdorf Guard Blue', brand: 'Citadel', range: 'Layer', type: 'layer', hex: '#1f56a7' },
  { name: 'Auric Armour Gold', brand: 'Citadel', range: 'Layer', type: 'layer', hex: '#c7a23c' },
  { name: 'Baharroth Blue', brand: 'Citadel', range: 'Layer', type: 'layer', hex: '#58c1cd' },
  { name: 'Baneblade Brown', brand: 'Citadel', range: 'Layer', type: 'layer', hex: '#937f6d' },
  { name: 'Cadian Fleshtone', brand: 'Citadel', range: 'Layer', type: 'layer', hex: '#c77958' },
  { name: 'Calgar Blue', brand: 'Citadel', range: 'Layer', type: 'layer', hex: '#4272b8' },
  { name: 'Dark Reaper', brand: 'Citadel', range: 'Layer', type: 'layer', hex: '#3b5150' },
  { name: 'Dawnstone', brand: 'Citadel', range: 'Layer', type: 'layer', hex: '#70756e' },
  { name: 'Doombull Brown', brand: 'Citadel', range: 'Layer', type: 'layer', hex: '#5c0009' },
  { name: 'Elysian Green', brand: 'Citadel', range: 'Layer', type: 'layer', hex: '#6b8c37' },
  { name: 'Eshin Grey', brand: 'Citadel', range: 'Layer', type: 'layer', hex: '#484b51' },
  { name: 'Evil Sunz Scarlet', brand: 'Citadel', range: 'Layer', type: 'layer', hex: '#c01411' },
  { name: 'Fenrisian Grey', brand: 'Citadel', range: 'Layer', type: 'layer', hex: '#6d94b3' },
  { name: 'Fire Dragon Bright', brand: 'Citadel', range: 'Layer', type: 'layer', hex: '#f4874e' },
  { name: 'Flash Gitz Yellow', brand: 'Citadel', range: 'Layer', type: 'layer', hex: '#fff300' },
  { name: 'Genestealer Purple', brand: 'Citadel', range: 'Layer', type: 'layer', hex: '#7658a5' },
  { name: 'Hoeth Blue', brand: 'Citadel', range: 'Layer', type: 'layer', hex: '#4c78af' },
  { name: 'Kabalite Green', brand: 'Citadel', range: 'Layer', type: 'layer', hex: '#038c67' },
  { name: 'Karak Stone', brand: 'Citadel', range: 'Layer', type: 'layer', hex: '#b7945c' },
  { name: 'Kislev Flesh', brand: 'Citadel', range: 'Layer', type: 'layer', hex: '#d6a875' },
  { name: 'Liberator Gold', brand: 'Citadel', range: 'Layer', type: 'layer', hex: '#c8a244' },
  { name: 'Loren Forest', brand: 'Citadel', range: 'Layer', type: 'layer', hex: '#486b25' },
  { name: 'Lothern Blue', brand: 'Citadel', range: 'Layer', type: 'layer', hex: '#2c9bcc' },
  { name: 'Moot Green', brand: 'Citadel', range: 'Layer', type: 'layer', hex: '#3daf44' },
  { name: 'Nurgling Green', brand: 'Citadel', range: 'Layer', type: 'layer', hex: '#849b62' },
  { name: 'Pallid Wych Flesh', brand: 'Citadel', range: 'Layer', type: 'layer', hex: '#cdcebe' },
  { name: 'Pink Horror', brand: 'Citadel', range: 'Layer', type: 'layer', hex: '#8e2757' },
  { name: 'Runefang Steel', brand: 'Citadel', range: 'Layer', type: 'layer', hex: '#a5a9ad' },
  { name: 'Screaming Skull', brand: 'Citadel', range: 'Layer', type: 'layer', hex: '#bfca7a' },
  { name: 'Skrag Brown', brand: 'Citadel', range: 'Layer', type: 'layer', hex: '#904601' },
  { name: 'Slaanesh Grey', brand: 'Citadel', range: 'Layer', type: 'layer', hex: '#8e8c97' },
  { name: 'Sotek Green', brand: 'Citadel', range: 'Layer', type: 'layer', hex: '#0b6974' },
  { name: 'Stormhost Silver', brand: 'Citadel', range: 'Layer', type: 'layer', hex: '#bbc6c9' },
  { name: 'Sybarite Green', brand: 'Citadel', range: 'Layer', type: 'layer', hex: '#17a166' },
  { name: 'Teclis Blue', brand: 'Citadel', range: 'Layer', type: 'layer', hex: '#317ec1' },
  { name: 'Temple Guard Blue', brand: 'Citadel', range: 'Layer', type: 'layer', hex: '#239489' },
  { name: 'Troll Slayer Orange', brand: 'Citadel', range: 'Layer', type: 'layer', hex: '#f36d22' },
  { name: 'Ulthuan Grey', brand: 'Citadel', range: 'Layer', type: 'layer', hex: '#c4ddd2' },
  { name: 'Ushabti Bone', brand: 'Citadel', range: 'Layer', type: 'layer', hex: '#bbbb7f' },
  { name: 'Warboss Green', brand: 'Citadel', range: 'Layer', type: 'layer', hex: '#317e57' },
  { name: 'Warpstone Glow', brand: 'Citadel', range: 'Layer', type: 'layer', hex: '#1e7331' },
  { name: 'White Scar', brand: 'Citadel', range: 'Layer', type: 'layer', hex: '#ffffff' },
  { name: 'Wild Rider Red', brand: 'Citadel', range: 'Layer', type: 'layer', hex: '#ea2f28' },
  { name: 'Xereus Purple', brand: 'Citadel', range: 'Layer', type: 'layer', hex: '#471f5f' },
  { name: 'Yriel Yellow', brand: 'Citadel', range: 'Layer', type: 'layer', hex: '#ffda00' },
];
