import type { PaintPreset } from './paints-citadel-base';

// Missing Speed Paint 2.0 colours + Speed Paint expansions
export const SPEED_PAINT_MISSING: PaintPreset[] = [
  { name: 'Hive Dweller Purple', brand: 'Army Painter', range: 'Speedpaint', type: 'contrast', hex: '#6a2878' },
  { name: 'Pastel Pink', brand: 'Army Painter', range: 'Speedpaint', type: 'contrast', hex: '#e8a0b8' },
  { name: 'Beguiling Red', brand: 'Army Painter', range: 'Speedpaint', type: 'contrast', hex: '#c01020' },
  { name: 'Vermillion Blaze', brand: 'Army Painter', range: 'Speedpaint', type: 'contrast', hex: '#d04020' },
  { name: 'Ochre Dunes', brand: 'Army Painter', range: 'Speedpaint', type: 'contrast', hex: '#c8a040' },
  { name: 'Sandstone', brand: 'Army Painter', range: 'Speedpaint', type: 'contrast', hex: '#d0b878' },
  { name: 'Troll Skin', brand: 'Army Painter', range: 'Speedpaint', type: 'contrast', hex: '#70a050' },
  { name: 'Swamp Scales', brand: 'Army Painter', range: 'Speedpaint', type: 'contrast', hex: '#2a5828' },
  { name: 'Toxic Waste', brand: 'Army Painter', range: 'Speedpaint', type: 'contrast', hex: '#80b020' },
  { name: 'Eldritch Teal', brand: 'Army Painter', range: 'Speedpaint', type: 'contrast', hex: '#006868' },
  { name: 'Glacier Blue', brand: 'Army Painter', range: 'Speedpaint', type: 'contrast', hex: '#60a8c0' },
  { name: 'Sapphire Blue', brand: 'Army Painter', range: 'Speedpaint', type: 'contrast', hex: '#1a3890' },
  { name: 'Ultramarine Blue', brand: 'Army Painter', range: 'Speedpaint', type: 'contrast', hex: '#1a3090' },
  { name: 'Drow Skin', brand: 'Army Painter', range: 'Speedpaint', type: 'contrast', hex: '#5a4870' },
  { name: 'Ashen Bone', brand: 'Army Painter', range: 'Speedpaint', type: 'contrast', hex: '#c8c0a0' },
  { name: 'Dusty Leather', brand: 'Army Painter', range: 'Speedpaint', type: 'contrast', hex: '#8a6838' },
  { name: 'Rust Brown', brand: 'Army Painter', range: 'Speedpaint', type: 'contrast', hex: '#7a4020' },
  { name: 'Charcoal', brand: 'Army Painter', range: 'Speedpaint', type: 'contrast', hex: '#383838' },
  { name: 'Ashen Grey', brand: 'Army Painter', range: 'Speedpaint', type: 'contrast', hex: '#a0a0a0' },
  { name: 'Warm Grey', brand: 'Army Painter', range: 'Speedpaint', type: 'contrast', hex: '#908878' },
  { name: 'Tainted Gold', brand: 'Army Painter', range: 'Speedpaint', type: 'contrast', hex: '#b09030' },
  { name: 'Burnished Bronze', brand: 'Army Painter', range: 'Speedpaint', type: 'contrast', hex: '#907030' },
  { name: 'Aged Iron', brand: 'Army Painter', range: 'Speedpaint', type: 'contrast', hex: '#585858' },
  { name: 'Bright Copper', brand: 'Army Painter', range: 'Speedpaint', type: 'contrast', hex: '#b87838' },
  { name: 'Polished Silver', brand: 'Army Painter', range: 'Speedpaint', type: 'contrast', hex: '#d0d0d0' },
  { name: 'Dusk Red', brand: 'Army Painter', range: 'Speedpaint', type: 'contrast', hex: '#6a0808' },
  { name: 'Verdant Green', brand: 'Army Painter', range: 'Speedpaint', type: 'contrast', hex: '#1a6828' },
  { name: 'Basilisk Skin', brand: 'Army Painter', range: 'Speedpaint', type: 'contrast', hex: '#5a8040' },
  { name: 'Wraith Cloth', brand: 'Army Painter', range: 'Speedpaint', type: 'contrast', hex: '#c0b8a0' },
  { name: 'Spectral Glow', brand: 'Army Painter', range: 'Speedpaint', type: 'contrast', hex: '#40d0a0' },
];
