import type { PaintPreset } from './paints-citadel-base';

export const VALLEJO_GAME: PaintPreset[] = [
  { name: 'Dead White', brand: 'Vallejo', range: 'Game Color', type: 'base', hex: '#ffffff' },
  { name: 'Bonewhite', brand: 'Vallejo', range: 'Game Color', type: 'base', hex: '#e8d4a2' },
  { name: 'Plague Brown', brand: 'Vallejo', range: 'Game Color', type: 'base', hex: '#9b8c3c' },
  { name: 'Gold Yellow', brand: 'Vallejo', range: 'Game Color', type: 'base', hex: '#f5b507' },
  { name: 'Sunblast Yellow', brand: 'Vallejo', range: 'Game Color', type: 'base', hex: '#ffed00' },
  { name: 'Hot Orange', brand: 'Vallejo', range: 'Game Color', type: 'base', hex: '#e55b12' },
  { name: 'Orange Fire', brand: 'Vallejo', range: 'Game Color', type: 'base', hex: '#e25c26' },
  { name: 'Bloody Red', brand: 'Vallejo', range: 'Game Color', type: 'base', hex: '#a91a1e' },
  { name: 'Scarlett Red', brand: 'Vallejo', range: 'Game Color', type: 'base', hex: '#900303' },
  { name: 'Gory Red', brand: 'Vallejo', range: 'Game Color', type: 'base', hex: '#6e0b05' },
  { name: 'Rosy Flesh', brand: 'Vallejo', range: 'Game Color', type: 'base', hex: '#d49d7a' },
  { name: 'Dwarf Skin', brand: 'Vallejo', range: 'Game Color', type: 'base', hex: '#c48a5e' },
  { name: 'Elf Skin Tone', brand: 'Vallejo', range: 'Game Color', type: 'base', hex: '#dba97f' },
  { name: 'Bronze Fleshtone', brand: 'Vallejo', range: 'Game Color', type: 'base', hex: '#a0714f' },
  { name: 'Squid Pink', brand: 'Vallejo', range: 'Game Color', type: 'base', hex: '#e86b8a' },
  { name: 'Warlord Purple', brand: 'Vallejo', range: 'Game Color', type: 'base', hex: '#6b2572' },
  { name: 'Hexed Lichen', brand: 'Vallejo', range: 'Game Color', type: 'base', hex: '#4b2b5c' },
  { name: 'Royal Purple', brand: 'Vallejo', range: 'Game Color', type: 'base', hex: '#5a1f6e' },
  { name: 'Stormy Blue', brand: 'Vallejo', range: 'Game Color', type: 'base', hex: '#4e6a8e' },
  { name: 'Ultra Marine Blue', brand: 'Vallejo', range: 'Game Color', type: 'base', hex: '#1f3fa6' },
  { name: 'Magic Blue', brand: 'Vallejo', range: 'Game Color', type: 'base', hex: '#1f5ea6' },
  { name: 'Electric Blue', brand: 'Vallejo', range: 'Game Color', type: 'base', hex: '#0089cf' },
  { name: 'Imperial Blue', brand: 'Vallejo', range: 'Game Color', type: 'base', hex: '#1a3050' },
  { name: 'Night Blue', brand: 'Vallejo', range: 'Game Color', type: 'base', hex: '#0a1838' },
  { name: 'Turquoise', brand: 'Vallejo', range: 'Game Color', type: 'base', hex: '#007a7a' },
  { name: 'Jade Green', brand: 'Vallejo', range: 'Game Color', type: 'base', hex: '#007a4a' },
  { name: 'Scurvy Green', brand: 'Vallejo', range: 'Game Color', type: 'base', hex: '#005c3a' },
  { name: 'Goblin Green', brand: 'Vallejo', range: 'Game Color', type: 'base', hex: '#3a8c2e' },
  { name: 'Sick Green', brand: 'Vallejo', range: 'Game Color', type: 'base', hex: '#8aa22c' },
  { name: 'Scorpy Green', brand: 'Vallejo', range: 'Game Color', type: 'base', hex: '#5cb82e' },
  { name: 'Dark Green', brand: 'Vallejo', range: 'Game Color', type: 'base', hex: '#003820' },
  { name: 'Cayman Green', brand: 'Vallejo', range: 'Game Color', type: 'base', hex: '#0e4e3a' },
  { name: 'Camouflage Green', brand: 'Vallejo', range: 'Game Color', type: 'base', hex: '#5a6830' },
  { name: 'Mutation Green', brand: 'Vallejo', range: 'Game Color', type: 'base', hex: '#4a6a20' },
  { name: 'Filthy Brown', brand: 'Vallejo', range: 'Game Color', type: 'base', hex: '#9a8030' },
  { name: 'Desert Yellow', brand: 'Vallejo', range: 'Game Color', type: 'base', hex: '#c8a848' },
  { name: 'Earth', brand: 'Vallejo', range: 'Game Color', type: 'base', hex: '#5c3a1e' },
  { name: 'Beasty Brown', brand: 'Vallejo', range: 'Game Color', type: 'base', hex: '#6b3a1a' },
  { name: 'Leather Brown', brand: 'Vallejo', range: 'Game Color', type: 'base', hex: '#7a5c3a' },
  { name: 'Charred Brown', brand: 'Vallejo', range: 'Game Color', type: 'base', hex: '#3a1a0a' },
  { name: 'Parasite Brown', brand: 'Vallejo', range: 'Game Color', type: 'base', hex: '#8a5020' },
  { name: 'Cobra Leather', brand: 'Vallejo', range: 'Game Color', type: 'base', hex: '#6a4020' },
  { name: 'Cold Grey', brand: 'Vallejo', range: 'Game Color', type: 'base', hex: '#7a8a8e' },
  { name: 'Stonewall Grey', brand: 'Vallejo', range: 'Game Color', type: 'base', hex: '#b4b0a6' },
  { name: 'Sombre Grey', brand: 'Vallejo', range: 'Game Color', type: 'base', hex: '#5a5e6a' },
  { name: 'Wolf Grey', brand: 'Vallejo', range: 'Game Color', type: 'base', hex: '#b4c4d0' },
  { name: 'Ghost Grey', brand: 'Vallejo', range: 'Game Color', type: 'base', hex: '#c8d0d8' },
  { name: 'Black', brand: 'Vallejo', range: 'Game Color', type: 'base', hex: '#0a0a0a' },
  { name: 'Chainmail Silver', brand: 'Vallejo', range: 'Game Color', type: 'base', hex: '#a8b0b4' },
  { name: 'Glorious Gold', brand: 'Vallejo', range: 'Game Color', type: 'base', hex: '#c4a030' },
  { name: 'Polished Gold', brand: 'Vallejo', range: 'Game Color', type: 'base', hex: '#d4a820' },
  { name: 'Bright Bronze', brand: 'Vallejo', range: 'Game Color', type: 'base', hex: '#a07030' },
  { name: 'Tinny Tin', brand: 'Vallejo', range: 'Game Color', type: 'base', hex: '#6a4a2a' },
  { name: 'Gunmetal', brand: 'Vallejo', range: 'Game Color', type: 'base', hex: '#5a6068' },
  { name: 'Hammered Copper', brand: 'Vallejo', range: 'Game Color', type: 'base', hex: '#b07838' },
  { name: 'Brassy Brass', brand: 'Vallejo', range: 'Game Color', type: 'base', hex: '#a08030' },
  { name: 'Black Wash', brand: 'Vallejo', range: 'Game Color Wash', type: 'shade', hex: '#141414' },
  { name: 'Umber Shade Wash', brand: 'Vallejo', range: 'Game Color Wash', type: 'shade', hex: '#5a3601' },
  { name: 'Sepia Wash', brand: 'Vallejo', range: 'Game Color Wash', type: 'shade', hex: '#c8a060' },
  { name: 'Red Wash', brand: 'Vallejo', range: 'Game Color Wash', type: 'shade', hex: '#8a1818' },
  { name: 'Green Wash', brand: 'Vallejo', range: 'Game Color Wash', type: 'shade', hex: '#1a5030' },
  { name: 'Blue Wash', brand: 'Vallejo', range: 'Game Color Wash', type: 'shade', hex: '#1a3870' },
  { name: 'Violet Wash', brand: 'Vallejo', range: 'Game Color Wash', type: 'shade', hex: '#5a1860' },
];

export const VALLEJO_MODEL: PaintPreset[] = [
  { name: 'White', brand: 'Vallejo', range: 'Model Color', type: 'base', hex: '#fafafa' },
  { name: 'Ivory', brand: 'Vallejo', range: 'Model Color', type: 'base', hex: '#f0e8c8' },
  { name: 'Deep Yellow', brand: 'Vallejo', range: 'Model Color', type: 'base', hex: '#e8a810' },
  { name: 'Golden Yellow', brand: 'Vallejo', range: 'Model Color', type: 'base', hex: '#f0c010' },
  { name: 'Flat Yellow', brand: 'Vallejo', range: 'Model Color', type: 'base', hex: '#f0d000' },
  { name: 'Ice Yellow', brand: 'Vallejo', range: 'Model Color', type: 'base', hex: '#f0e880' },
  { name: 'Lemon Yellow', brand: 'Vallejo', range: 'Model Color', type: 'base', hex: '#f8f040' },
  { name: 'Orange Brown', brand: 'Vallejo', range: 'Model Color', type: 'base', hex: '#c06020' },
  { name: 'Flat Orange', brand: 'Vallejo', range: 'Model Color', type: 'base', hex: '#e06020' },
  { name: 'Light Orange', brand: 'Vallejo', range: 'Model Color', type: 'base', hex: '#e88040' },
  { name: 'Vermillion', brand: 'Vallejo', range: 'Model Color', type: 'base', hex: '#d03020' },
  { name: 'Flat Red', brand: 'Vallejo', range: 'Model Color', type: 'base', hex: '#b01810' },
  { name: 'Scarlet', brand: 'Vallejo', range: 'Model Color', type: 'base', hex: '#c82020' },
  { name: 'Carmine Red', brand: 'Vallejo', range: 'Model Color', type: 'base', hex: '#8a0808' },
  { name: 'Dark Red', brand: 'Vallejo', range: 'Model Color', type: 'base', hex: '#6a0808' },
  { name: 'Cavalry Brown', brand: 'Vallejo', range: 'Model Color', type: 'base', hex: '#5a2810' },
  { name: 'Magenta', brand: 'Vallejo', range: 'Model Color', type: 'base', hex: '#a01050' },
  { name: 'Purple', brand: 'Vallejo', range: 'Model Color', type: 'base', hex: '#5a1878' },
  { name: 'Blue Violet', brand: 'Vallejo', range: 'Model Color', type: 'base', hex: '#3a2080' },
  { name: 'Royal Blue', brand: 'Vallejo', range: 'Model Color', type: 'base', hex: '#1a3090' },
  { name: 'Ultramarine', brand: 'Vallejo', range: 'Model Color', type: 'base', hex: '#1a2878' },
  { name: 'Dark Blue', brand: 'Vallejo', range: 'Model Color', type: 'base', hex: '#0a1850' },
  { name: 'Flat Blue', brand: 'Vallejo', range: 'Model Color', type: 'base', hex: '#2050a0' },
  { name: 'Medium Blue', brand: 'Vallejo', range: 'Model Color', type: 'base', hex: '#3070c0' },
  { name: 'Sky Blue', brand: 'Vallejo', range: 'Model Color', type: 'base', hex: '#6098c8' },
  { name: 'Andrea Blue', brand: 'Vallejo', range: 'Model Color', type: 'base', hex: '#2868a0' },
  { name: 'Dark Prussian Blue', brand: 'Vallejo', range: 'Model Color', type: 'base', hex: '#0a2040' },
  { name: 'Light Turquoise', brand: 'Vallejo', range: 'Model Color', type: 'base', hex: '#40a8b0' },
  { name: 'Pastel Green', brand: 'Vallejo', range: 'Model Color', type: 'base', hex: '#80c080' },
  { name: 'Dark Green', brand: 'Vallejo', range: 'Model Color', type: 'base', hex: '#003818' },
  { name: 'Olive Green', brand: 'Vallejo', range: 'Model Color', type: 'base', hex: '#3a4820' },
  { name: 'Flat Green', brand: 'Vallejo', range: 'Model Color', type: 'base', hex: '#2a6030' },
  { name: 'Medium Olive', brand: 'Vallejo', range: 'Model Color', type: 'base', hex: '#4a5828' },
  { name: 'Lime Green', brand: 'Vallejo', range: 'Model Color', type: 'base', hex: '#68a030' },
  { name: 'Park Green Flat', brand: 'Vallejo', range: 'Model Color', type: 'base', hex: '#3a8838' },
  { name: 'Intermediate Green', brand: 'Vallejo', range: 'Model Color', type: 'base', hex: '#286828' },
  { name: 'Reflective Green', brand: 'Vallejo', range: 'Model Color', type: 'base', hex: '#003010' },
  { name: 'Flat Earth', brand: 'Vallejo', range: 'Model Color', type: 'base', hex: '#7a5830' },
  { name: 'Flat Brown', brand: 'Vallejo', range: 'Model Color', type: 'base', hex: '#5a3818' },
  { name: 'Chocolate Brown', brand: 'Vallejo', range: 'Model Color', type: 'base', hex: '#3a2010' },
  { name: 'German Camo Black Brown', brand: 'Vallejo', range: 'Model Color', type: 'base', hex: '#2a1808' },
  { name: 'Burnt Umber', brand: 'Vallejo', range: 'Model Color', type: 'base', hex: '#5a3020' },
  { name: 'Mahogany Brown', brand: 'Vallejo', range: 'Model Color', type: 'base', hex: '#4a2018' },
  { name: 'Buff', brand: 'Vallejo', range: 'Model Color', type: 'base', hex: '#d0b878' },
  { name: 'Dark Sand', brand: 'Vallejo', range: 'Model Color', type: 'base', hex: '#c0a060' },
  { name: 'Iraqi Sand', brand: 'Vallejo', range: 'Model Color', type: 'base', hex: '#d0b880' },
  { name: 'Deck Tan', brand: 'Vallejo', range: 'Model Color', type: 'base', hex: '#b89870' },
  { name: 'Flat Flesh', brand: 'Vallejo', range: 'Model Color', type: 'base', hex: '#c89068' },
  { name: 'Beige Red', brand: 'Vallejo', range: 'Model Color', type: 'base', hex: '#c08060' },
  { name: 'Basic Skin Tone', brand: 'Vallejo', range: 'Model Color', type: 'base', hex: '#c8a080' },
  { name: 'Light Flesh', brand: 'Vallejo', range: 'Model Color', type: 'base', hex: '#d8b898' },
  { name: 'Black Grey', brand: 'Vallejo', range: 'Model Color', type: 'base', hex: '#3a3a3a' },
  { name: 'German Grey', brand: 'Vallejo', range: 'Model Color', type: 'base', hex: '#4a4a48' },
  { name: 'Neutral Grey', brand: 'Vallejo', range: 'Model Color', type: 'base', hex: '#808080' },
  { name: 'Light Grey', brand: 'Vallejo', range: 'Model Color', type: 'base', hex: '#b0b0b0' },
  { name: 'Basalt Grey', brand: 'Vallejo', range: 'Model Color', type: 'base', hex: '#585858' },
  { name: 'London Grey', brand: 'Vallejo', range: 'Model Color', type: 'base', hex: '#9a9a98' },
  { name: 'Silver', brand: 'Vallejo', range: 'Model Color', type: 'base', hex: '#c0c0c0' },
  { name: 'Gold', brand: 'Vallejo', range: 'Model Color', type: 'base', hex: '#c8a830' },
  { name: 'Copper', brand: 'Vallejo', range: 'Model Color', type: 'base', hex: '#b07030' },
  { name: 'Old Gold', brand: 'Vallejo', range: 'Model Color', type: 'base', hex: '#b09030' },
  { name: 'Gunmetal Grey', brand: 'Vallejo', range: 'Model Color', type: 'base', hex: '#586068' },
  { name: 'Natural Steel', brand: 'Vallejo', range: 'Model Color', type: 'base', hex: '#909898' },
  { name: 'Oily Steel', brand: 'Vallejo', range: 'Model Color', type: 'base', hex: '#687078' },
  { name: 'Bronze', brand: 'Vallejo', range: 'Model Color', type: 'base', hex: '#8a6028' },
  { name: 'Brass', brand: 'Vallejo', range: 'Model Color', type: 'base', hex: '#a08830' },
  { name: 'Black', brand: 'Vallejo', range: 'Model Color', type: 'base', hex: '#0a0a0a' },
];
