import type { PaintPreset } from './paints-citadel-base';

export const VALLEJO_XPRESS: PaintPreset[] = [
  { name: 'Imperial Yellow', brand: 'Vallejo', range: 'Xpress Color', type: 'contrast', hex: '#f0c010' },
  { name: 'Nuclear Yellow', brand: 'Vallejo', range: 'Xpress Color', type: 'contrast', hex: '#e8d020' },
  { name: 'Solar Orange', brand: 'Vallejo', range: 'Xpress Color', type: 'contrast', hex: '#e06020' },
  { name: 'Martian Orange', brand: 'Vallejo', range: 'Xpress Color', type: 'contrast', hex: '#c04818' },
  { name: 'Plasma Red', brand: 'Vallejo', range: 'Xpress Color', type: 'contrast', hex: '#b01010' },
  { name: 'Velvet Red', brand: 'Vallejo', range: 'Xpress Color', type: 'contrast', hex: '#8a0808' },
  { name: 'Gloomy Violet', brand: 'Vallejo', range: 'Xpress Color', type: 'contrast', hex: '#4a1860' },
  { name: 'Storm Blue', brand: 'Vallejo', range: 'Xpress Color', type: 'contrast', hex: '#1a3090' },
  { name: 'Caribbean Turquoise', brand: 'Vallejo', range: 'Xpress Color', type: 'contrast', hex: '#008888' },
  { name: 'Heretic Turquoise', brand: 'Vallejo', range: 'Xpress Color', type: 'contrast', hex: '#006060' },
  { name: 'Orc Skin', brand: 'Vallejo', range: 'Xpress Color', type: 'contrast', hex: '#4a7830' },
  { name: 'Plague Green', brand: 'Vallejo', range: 'Xpress Color', type: 'contrast', hex: '#6a7838' },
  { name: 'Camouflage Green', brand: 'Vallejo', range: 'Xpress Color', type: 'contrast', hex: '#3a5020' },
  { name: 'Wasteland Brown', brand: 'Vallejo', range: 'Xpress Color', type: 'contrast', hex: '#6a4020' },
  { name: 'Muddy Ground', brand: 'Vallejo', range: 'Xpress Color', type: 'contrast', hex: '#5a3818' },
  { name: 'Willow Bark', brand: 'Vallejo', range: 'Xpress Color', type: 'contrast', hex: '#3a2010' },
  { name: 'Dwarf Skin', brand: 'Vallejo', range: 'Xpress Color', type: 'contrast', hex: '#c48a5e' },
  { name: 'Tanned Skin', brand: 'Vallejo', range: 'Xpress Color', type: 'contrast', hex: '#a07050' },
  { name: 'Templar White', brand: 'Vallejo', range: 'Xpress Color', type: 'contrast', hex: '#e8e8e8' },
  { name: 'Omega Blue', brand: 'Vallejo', range: 'Xpress Color', type: 'contrast', hex: '#2050a0' },
  { name: 'Space Grey', brand: 'Vallejo', range: 'Xpress Color', type: 'contrast', hex: '#606868' },
  { name: 'Landser Grey', brand: 'Vallejo', range: 'Xpress Color', type: 'contrast', hex: '#4a5058' },
  { name: 'Viking Grey', brand: 'Vallejo', range: 'Xpress Color', type: 'contrast', hex: '#808890' },
  { name: 'Hospitallier White', brand: 'Vallejo', range: 'Xpress Color', type: 'contrast', hex: '#d8d8d8' },
  { name: 'Copper Brown', brand: 'Vallejo', range: 'Xpress Color', type: 'contrast', hex: '#8a5828' },
  { name: 'Battledress Green', brand: 'Vallejo', range: 'Xpress Color', type: 'contrast', hex: '#2a4818' },
  { name: 'Cardinal Purple', brand: 'Vallejo', range: 'Xpress Color', type: 'contrast', hex: '#5a1878' },
  { name: 'Wicked Pink', brand: 'Vallejo', range: 'Xpress Color', type: 'contrast', hex: '#c04080' },
  { name: 'Intense Blue', brand: 'Vallejo', range: 'Xpress Color', type: 'contrast', hex: '#0060c0' },
  { name: 'Black Lotus', brand: 'Vallejo', range: 'Xpress Color', type: 'contrast', hex: '#1a1a1a' },
];

export const CITADEL_MISSING: PaintPreset[] = [
  // Missing Base paints
  { name: 'Lupercal Green', brand: 'Citadel', range: 'Base', type: 'base', hex: '#002c2b' },
  { name: 'Night Lords Blue', brand: 'Citadel', range: 'Base', type: 'base', hex: '#002b5c' },
  { name: 'Catachan Fleshtone', brand: 'Citadel', range: 'Base', type: 'base', hex: '#6a4c2d' },
  { name: 'Hobgrot Hide', brand: 'Citadel', range: 'Base', type: 'base', hex: '#b09060' },
  { name: 'Orruk Flesh', brand: 'Citadel', range: 'Base', type: 'base', hex: '#7a8a40' },
  // Missing Layer paints
  { name: 'Bestigor Flesh', brand: 'Citadel', range: 'Layer', type: 'layer', hex: '#d38a57' },
  { name: 'Deepkin Flesh', brand: 'Citadel', range: 'Layer', type: 'layer', hex: '#a9bfbb' },
  { name: 'Flayed One Flesh', brand: 'Citadel', range: 'Layer', type: 'layer', hex: '#eec483' },
  { name: 'Fulgurite Copper', brand: 'Citadel', range: 'Layer', type: 'layer', hex: '#6d4730' },
  { name: 'Gauss Blaster Green', brand: 'Citadel', range: 'Layer', type: 'layer', hex: '#84c3aa' },
  { name: 'Hashut Copper', brand: 'Citadel', range: 'Layer', type: 'layer', hex: '#b56336' },
  { name: 'Knight-Questor Flesh', brand: 'Citadel', range: 'Layer', type: 'layer', hex: '#b86036' },
  { name: 'Ogryn Camo', brand: 'Citadel', range: 'Layer', type: 'layer', hex: '#9da94b' },
  { name: 'Skarsnik Green', brand: 'Citadel', range: 'Layer', type: 'layer', hex: '#5f9370' },
  { name: 'Straken Green', brand: 'Citadel', range: 'Layer', type: 'layer', hex: '#628126' },
  { name: 'Tallarn Sand', brand: 'Citadel', range: 'Layer', type: 'layer', hex: '#a67610' },
  { name: 'Tau Light Ochre', brand: 'Citadel', range: 'Layer', type: 'layer', hex: '#bf6e1d' },
  { name: 'Ungor Flesh', brand: 'Citadel', range: 'Layer', type: 'layer', hex: '#d6a766' },
  { name: 'Zamesi Desert', brand: 'Citadel', range: 'Layer', type: 'layer', hex: '#dda026' },
  // Missing Shade
  { name: 'Soulblight Grey', brand: 'Citadel', range: 'Shade', type: 'shade', hex: '#6b6b6b' },
];
