import type { PaintType } from '../types';
export interface PaintPreset { name: string; brand: string; range: string; type: PaintType; hex: string; }

export const CITADEL_BASE: PaintPreset[] = [
  { name: 'Abaddon Black', brand: 'Citadel', range: 'Base', type: 'base', hex: '#231f20' },
  { name: 'Averland Sunset', brand: 'Citadel', range: 'Base', type: 'base', hex: '#fdb825' },
  { name: 'Balthasar Gold', brand: 'Citadel', range: 'Base', type: 'base', hex: '#a47552' },
  { name: 'Bugmans Glow', brand: 'Citadel', range: 'Base', type: 'base', hex: '#834f44' },
  { name: 'Caledor Sky', brand: 'Citadel', range: 'Base', type: 'base', hex: '#366699' },
  { name: 'Caliban Green', brand: 'Citadel', range: 'Base', type: 'base', hex: '#003d15' },
  { name: 'Castellan Green', brand: 'Citadel', range: 'Base', type: 'base', hex: '#264715' },
  { name: 'Celestra Grey', brand: 'Citadel', range: 'Base', type: 'base', hex: '#90a8a8' },
  { name: 'Corax White', brand: 'Citadel', range: 'Base', type: 'base', hex: '#ffffff' },
  { name: 'Daemonette Hide', brand: 'Citadel', range: 'Base', type: 'base', hex: '#696684' },
  { name: 'Death Guard Green', brand: 'Citadel', range: 'Base', type: 'base', hex: '#6d6e48' },
  { name: 'Deathworld Forest', brand: 'Citadel', range: 'Base', type: 'base', hex: '#5c6730' },
  { name: 'Dryad Bark', brand: 'Citadel', range: 'Base', type: 'base', hex: '#33312d' },
  { name: 'Grey Knights Steel', brand: 'Citadel', range: 'Base', type: 'base', hex: '#6d7c8b' },
  { name: 'Grey Seer', brand: 'Citadel', range: 'Base', type: 'base', hex: '#a2a5a7' },
  { name: 'Incubi Darkness', brand: 'Citadel', range: 'Base', type: 'base', hex: '#0b474a' },
  { name: 'Iron Hands Steel', brand: 'Citadel', range: 'Base', type: 'base', hex: '#44423f' },
  { name: 'Iron Warriors', brand: 'Citadel', range: 'Base', type: 'base', hex: '#414141' },
  { name: 'Jokaero Orange', brand: 'Citadel', range: 'Base', type: 'base', hex: '#ee3823' },
  { name: 'Kantor Blue', brand: 'Citadel', range: 'Base', type: 'base', hex: '#02134e' },
  { name: 'Khorne Red', brand: 'Citadel', range: 'Base', type: 'base', hex: '#6a0001' },
  { name: 'Leadbelcher', brand: 'Citadel', range: 'Base', type: 'base', hex: '#888d91' },
  { name: 'Macragge Blue', brand: 'Citadel', range: 'Base', type: 'base', hex: '#0d407f' },
  { name: 'Mechanicus Standard Grey', brand: 'Citadel', range: 'Base', type: 'base', hex: '#3d4b4d' },
  { name: 'Mephiston Red', brand: 'Citadel', range: 'Base', type: 'base', hex: '#9a1115' },
  { name: 'Morghast Bone', brand: 'Citadel', range: 'Base', type: 'base', hex: '#c1a57d' },
  { name: 'Mournfang Brown', brand: 'Citadel', range: 'Base', type: 'base', hex: '#640909' },
  { name: 'Naggaroth Night', brand: 'Citadel', range: 'Base', type: 'base', hex: '#3b2b50' },
  { name: 'Phoenician Purple', brand: 'Citadel', range: 'Base', type: 'base', hex: '#440052' },
  { name: 'Rakarth Flesh', brand: 'Citadel', range: 'Base', type: 'base', hex: '#a29e91' },
  { name: 'Retributor Armour', brand: 'Citadel', range: 'Base', type: 'base', hex: '#c39e5a' },
  { name: 'Rhinox Hide', brand: 'Citadel', range: 'Base', type: 'base', hex: '#462f30' },
  { name: 'Screamer Pink', brand: 'Citadel', range: 'Base', type: 'base', hex: '#7c1645' },
  { name: 'Steel Legion Drab', brand: 'Citadel', range: 'Base', type: 'base', hex: '#584e2d' },
  { name: 'Stegadon Scale Green', brand: 'Citadel', range: 'Base', type: 'base', hex: '#074863' },
  { name: 'The Fang', brand: 'Citadel', range: 'Base', type: 'base', hex: '#405b71' },
  { name: 'Thousand Sons Blue', brand: 'Citadel', range: 'Base', type: 'base', hex: '#00506f' },
  { name: 'Warplock Bronze', brand: 'Citadel', range: 'Base', type: 'base', hex: '#927d7b' },
  { name: 'Wraithbone', brand: 'Citadel', range: 'Base', type: 'base', hex: '#dbd1b2' },
  { name: 'XV-88', brand: 'Citadel', range: 'Base', type: 'base', hex: '#72491e' },
  { name: 'Zandri Dust', brand: 'Citadel', range: 'Base', type: 'base', hex: '#9e915c' },
];
