import type { PaintPreset } from './paints-citadel-base';

export const CITADEL_AIR: PaintPreset[] = [
  { name: 'Mephiston Red Air', brand: 'Citadel', range: 'Air', type: 'air', hex: '#9a1115' },
  { name: 'Khorne Red Air', brand: 'Citadel', range: 'Air', type: 'air', hex: '#6a0001' },
  { name: 'Macragge Blue Air', brand: 'Citadel', range: 'Air', type: 'air', hex: '#0d407f' },
  { name: 'Caliban Green Air', brand: 'Citadel', range: 'Air', type: 'air', hex: '#003d15' },
  { name: 'Zandri Dust Air', brand: 'Citadel', range: 'Air', type: 'air', hex: '#9e915c' },
  { name: 'Leadbelcher Air', brand: 'Citadel', range: 'Air', type: 'air', hex: '#888d91' },
  { name: 'Retributor Armour Air', brand: 'Citadel', range: 'Air', type: 'air', hex: '#c39e5a' },
  { name: 'Abaddon Black Air', brand: 'Citadel', range: 'Air', type: 'air', hex: '#231f20' },
  { name: 'Wraithbone Air', brand: 'Citadel', range: 'Air', type: 'air', hex: '#dbd1b2' },
  { name: 'Grey Seer Air', brand: 'Citadel', range: 'Air', type: 'air', hex: '#a2a5a7' },
  { name: 'Mechanicus Standard Grey Air', brand: 'Citadel', range: 'Air', type: 'air', hex: '#3d4b4d' },
  { name: 'Averland Sunset Air', brand: 'Citadel', range: 'Air', type: 'air', hex: '#fdb825' },
  { name: 'Balthasar Gold Air', brand: 'Citadel', range: 'Air', type: 'air', hex: '#a47552' },
  { name: 'Corax White Air', brand: 'Citadel', range: 'Air', type: 'air', hex: '#ffffff' },
  { name: 'Naggaroth Night Air', brand: 'Citadel', range: 'Air', type: 'air', hex: '#3b2b50' },
  { name: 'The Fang Air', brand: 'Citadel', range: 'Air', type: 'air', hex: '#405b71' },
  { name: 'Deathworld Forest Air', brand: 'Citadel', range: 'Air', type: 'air', hex: '#5c6730' },
  { name: 'Mournfang Brown Air', brand: 'Citadel', range: 'Air', type: 'air', hex: '#640909' },
  { name: 'Steel Legion Drab Air', brand: 'Citadel', range: 'Air', type: 'air', hex: '#584e2d' },
  { name: 'Castellan Green Air', brand: 'Citadel', range: 'Air', type: 'air', hex: '#264715' },
];

export const PROACRYL: PaintPreset[] = [
  { name: 'Bold Titanium White', brand: 'ProAcryl', range: 'ProAcryl', type: 'base', hex: '#ffffff' },
  { name: 'Ivory', brand: 'ProAcryl', range: 'ProAcryl', type: 'base', hex: '#f0e8c8' },
  { name: 'Golden Yellow', brand: 'ProAcryl', range: 'ProAcryl', type: 'base', hex: '#f0c010' },
  { name: 'Orange', brand: 'ProAcryl', range: 'ProAcryl', type: 'base', hex: '#e06020' },
  { name: 'Pyrrole Red', brand: 'ProAcryl', range: 'ProAcryl', type: 'base', hex: '#c01010' },
  { name: 'Crimson', brand: 'ProAcryl', range: 'ProAcryl', type: 'base', hex: '#8a0808' },
  { name: 'Magenta', brand: 'ProAcryl', range: 'ProAcryl', type: 'base', hex: '#a01050' },
  { name: 'Dark Violet', brand: 'ProAcryl', range: 'ProAcryl', type: 'base', hex: '#3a1060' },
  { name: 'Ultramarine Blue', brand: 'ProAcryl', range: 'ProAcryl', type: 'base', hex: '#1a3090' },
  { name: 'Cobalt Blue', brand: 'ProAcryl', range: 'ProAcryl', type: 'base', hex: '#2050a0' },
  { name: 'Turquoise', brand: 'ProAcryl', range: 'ProAcryl', type: 'base', hex: '#008888' },
  { name: 'Dark Green', brand: 'ProAcryl', range: 'ProAcryl', type: 'base', hex: '#003818' },
  { name: 'Bright Green', brand: 'ProAcryl', range: 'ProAcryl', type: 'base', hex: '#3a8830' },
  { name: 'Yellow Green', brand: 'ProAcryl', range: 'ProAcryl', type: 'base', hex: '#68a030' },
  { name: 'Burnt Umber', brand: 'ProAcryl', range: 'ProAcryl', type: 'base', hex: '#5a3020' },
  { name: 'Raw Sienna', brand: 'ProAcryl', range: 'ProAcryl', type: 'base', hex: '#b08040' },
  { name: 'Flesh', brand: 'ProAcryl', range: 'ProAcryl', type: 'base', hex: '#c89068' },
  { name: 'Dark Flesh', brand: 'ProAcryl', range: 'ProAcryl', type: 'base', hex: '#8a5830' },
  { name: 'Neutral Grey', brand: 'ProAcryl', range: 'ProAcryl', type: 'base', hex: '#808080' },
  { name: 'Dark Neutral Grey', brand: 'ProAcryl', range: 'ProAcryl', type: 'base', hex: '#404040' },
  { name: 'Coal Black', brand: 'ProAcryl', range: 'ProAcryl', type: 'base', hex: '#1a1a1a' },
  { name: 'Silver', brand: 'ProAcryl', range: 'ProAcryl', type: 'base', hex: '#c0c0c0' },
  { name: 'Rich Gold', brand: 'ProAcryl', range: 'ProAcryl', type: 'base', hex: '#c8a830' },
  { name: 'Copper', brand: 'ProAcryl', range: 'ProAcryl', type: 'base', hex: '#b07030' },
];

export const SCALE75: PaintPreset[] = [
  { name: 'White', brand: 'Scale75', range: 'Fantasy & Games', type: 'base', hex: '#fafafa' },
  { name: 'Sahara Yellow', brand: 'Scale75', range: 'Fantasy & Games', type: 'base', hex: '#d8b040' },
  { name: 'Sol Yellow', brand: 'Scale75', range: 'Fantasy & Games', type: 'base', hex: '#f0c010' },
  { name: 'Blood Red', brand: 'Scale75', range: 'Fantasy & Games', type: 'base', hex: '#b01010' },
  { name: 'Antares Red', brand: 'Scale75', range: 'Fantasy & Games', type: 'base', hex: '#8a0808' },
  { name: 'Violet', brand: 'Scale75', range: 'Fantasy & Games', type: 'base', hex: '#5a1878' },
  { name: 'Innsmouth Blue', brand: 'Scale75', range: 'Fantasy & Games', type: 'base', hex: '#1a3090' },
  { name: 'Caribbean Blue', brand: 'Scale75', range: 'Fantasy & Games', type: 'base', hex: '#2080c0' },
  { name: 'Bering Blue', brand: 'Scale75', range: 'Fantasy & Games', type: 'base', hex: '#0a2040' },
  { name: 'Spring Green', brand: 'Scale75', range: 'Fantasy & Games', type: 'base', hex: '#3a8830' },
  { name: 'Sherwood Green', brand: 'Scale75', range: 'Fantasy & Games', type: 'base', hex: '#003818' },
  { name: 'Birch', brand: 'Scale75', range: 'Fantasy & Games', type: 'base', hex: '#b09060' },
  { name: 'Leather Brown', brand: 'Scale75', range: 'Fantasy & Games', type: 'base', hex: '#7a5830' },
  { name: 'Black Leather', brand: 'Scale75', range: 'Fantasy & Games', type: 'base', hex: '#2a1808' },
  { name: 'Graphite', brand: 'Scale75', range: 'Fantasy & Games', type: 'base', hex: '#404040' },
  { name: 'Abyssal Blue', brand: 'Scale75', range: 'Fantasy & Games', type: 'base', hex: '#0a1838' },
  { name: 'Black', brand: 'Scale75', range: 'Fantasy & Games', type: 'base', hex: '#0a0a0a' },
  { name: 'Elven Gold', brand: 'Scale75', range: 'Metal n Alchemy', type: 'base', hex: '#c8a830' },
  { name: 'Dwarven Gold', brand: 'Scale75', range: 'Metal n Alchemy', type: 'base', hex: '#a08030' },
  { name: 'Speed Metal', brand: 'Scale75', range: 'Metal n Alchemy', type: 'base', hex: '#c0c0c0' },
  { name: 'Thrash Metal', brand: 'Scale75', range: 'Metal n Alchemy', type: 'base', hex: '#909090' },
  { name: 'Heavy Metal', brand: 'Scale75', range: 'Metal n Alchemy', type: 'base', hex: '#686868' },
  { name: 'Victorian Brass', brand: 'Scale75', range: 'Metal n Alchemy', type: 'base', hex: '#a08838' },
  { name: 'Copper', brand: 'Scale75', range: 'Metal n Alchemy', type: 'base', hex: '#b07030' },
];
