import type { PaintPreset } from './paints-citadel-base';

export const CITADEL_SHADE: PaintPreset[] = [
  { name: 'Agrax Earthshade', brand: 'Citadel', range: 'Shade', type: 'shade', hex: '#5a3601' },
  { name: 'Biel-Tan Green', brand: 'Citadel', range: 'Shade', type: 'shade', hex: '#1ba169' },
  { name: 'Carroburg Crimson', brand: 'Citadel', range: 'Shade', type: 'shade', hex: '#a8255a' },
  { name: 'Casandora Yellow', brand: 'Citadel', range: 'Shade', type: 'shade', hex: '#f4b400' },
  { name: 'Coelia Greenshade', brand: 'Citadel', range: 'Shade', type: 'shade', hex: '#0e7f78' },
  { name: 'Drakenhof Nightshade', brand: 'Citadel', range: 'Shade', type: 'shade', hex: '#125899' },
  { name: 'Druchii Violet', brand: 'Citadel', range: 'Shade', type: 'shade', hex: '#7a468c' },
  { name: 'Fuegan Orange', brand: 'Citadel', range: 'Shade', type: 'shade', hex: '#c77e0c' },
  { name: 'Nuln Oil', brand: 'Citadel', range: 'Shade', type: 'shade', hex: '#14100e' },
  { name: 'Reikland Fleshshade', brand: 'Citadel', range: 'Shade', type: 'shade', hex: '#ca6c4d' },
  { name: 'Seraphim Sepia', brand: 'Citadel', range: 'Shade', type: 'shade', hex: '#d7824a' },
];

export const CITADEL_CONTRAST: PaintPreset[] = [
  { name: 'Aethermatic Blue', brand: 'Citadel', range: 'Contrast', type: 'contrast', hex: '#79bcc8' },
  { name: 'Aggaros Dunes', brand: 'Citadel', range: 'Contrast', type: 'contrast', hex: '#d4a94e' },
  { name: 'Akhelian Green', brand: 'Citadel', range: 'Contrast', type: 'contrast', hex: '#3b8376' },
  { name: 'Apothecary White', brand: 'Citadel', range: 'Contrast', type: 'contrast', hex: '#c5cfd2' },
  { name: 'Basilicanum Grey', brand: 'Citadel', range: 'Contrast', type: 'contrast', hex: '#989897' },
  { name: 'Black Legion', brand: 'Citadel', range: 'Contrast', type: 'contrast', hex: '#1c1e22' },
  { name: 'Black Templar', brand: 'Citadel', range: 'Contrast', type: 'contrast', hex: '#1c1e22' },
  { name: 'Blood Angels Red', brand: 'Citadel', range: 'Contrast', type: 'contrast', hex: '#c11519' },
  { name: 'Briar Queen Chill', brand: 'Citadel', range: 'Contrast', type: 'contrast', hex: '#5b8a8f' },
  { name: 'Creed Camo', brand: 'Citadel', range: 'Contrast', type: 'contrast', hex: '#5c7a3b' },
  { name: 'Cygor Brown', brand: 'Citadel', range: 'Contrast', type: 'contrast', hex: '#6e4b31' },
  { name: 'Dark Angels Green', brand: 'Citadel', range: 'Contrast', type: 'contrast', hex: '#004e2a' },
  { name: 'Darkoath Flesh', brand: 'Citadel', range: 'Contrast', type: 'contrast', hex: '#c48a5e' },
  { name: 'Flesh Tearers Red', brand: 'Citadel', range: 'Contrast', type: 'contrast', hex: '#880808' },
  { name: 'Fyreslayer Flesh', brand: 'Citadel', range: 'Contrast', type: 'contrast', hex: '#c87840' },
  { name: 'Gore-Grunta Fur', brand: 'Citadel', range: 'Contrast', type: 'contrast', hex: '#6e3b2a' },
  { name: 'Gryph-Charger Grey', brand: 'Citadel', range: 'Contrast', type: 'contrast', hex: '#6e8ba4' },
  { name: 'Gryph-Hound Orange', brand: 'Citadel', range: 'Contrast', type: 'contrast', hex: '#d86a1a' },
  { name: 'Guilliman Flesh', brand: 'Citadel', range: 'Contrast', type: 'contrast', hex: '#d1a570' },
  { name: 'Hexwraith Flame', brand: 'Citadel', range: 'Contrast', type: 'contrast', hex: '#5a9c5a' },
  { name: 'Iyanden Yellow', brand: 'Citadel', range: 'Contrast', type: 'contrast', hex: '#fdc31b' },
  { name: 'Karandras Green', brand: 'Citadel', range: 'Contrast', type: 'contrast', hex: '#2a5c2a' },
  { name: 'Leviadon Blue', brand: 'Citadel', range: 'Contrast', type: 'contrast', hex: '#002d59' },
  { name: 'Luxion Purple', brand: 'Citadel', range: 'Contrast', type: 'contrast', hex: '#6a2a8a' },
  { name: 'Magos Purple', brand: 'Citadel', range: 'Contrast', type: 'contrast', hex: '#a05da5' },
  { name: 'Militarum Green', brand: 'Citadel', range: 'Contrast', type: 'contrast', hex: '#7a7d45' },
  { name: 'Nazdreg Yellow', brand: 'Citadel', range: 'Contrast', type: 'contrast', hex: '#c28f0e' },
  { name: 'Ork Flesh', brand: 'Citadel', range: 'Contrast', type: 'contrast', hex: '#3e7a35' },
  { name: 'Plaguebearer Flesh', brand: 'Citadel', range: 'Contrast', type: 'contrast', hex: '#c4d29b' },
  { name: 'Pylar Glacier', brand: 'Citadel', range: 'Contrast', type: 'contrast', hex: '#4ac8e0' },
  { name: 'Ratling Grime', brand: 'Citadel', range: 'Contrast', type: 'contrast', hex: '#5a4a30' },
  { name: 'Shyish Purple', brand: 'Citadel', range: 'Contrast', type: 'contrast', hex: '#5a3667' },
  { name: 'Skeleton Horde', brand: 'Citadel', range: 'Contrast', type: 'contrast', hex: '#c4a96a' },
  { name: 'Snakebite Leather', brand: 'Citadel', range: 'Contrast', type: 'contrast', hex: '#9c6b08' },
  { name: 'Space Wolves Grey', brand: 'Citadel', range: 'Contrast', type: 'contrast', hex: '#8ba9c4' },
  { name: 'Striking Scorpion Green', brand: 'Citadel', range: 'Contrast', type: 'contrast', hex: '#5d9b37' },
  { name: 'Talassar Blue', brand: 'Citadel', range: 'Contrast', type: 'contrast', hex: '#0060a8' },
  { name: 'Terradon Turquoise', brand: 'Citadel', range: 'Contrast', type: 'contrast', hex: '#006d6f' },
  { name: 'Ultramarines Blue', brand: 'Citadel', range: 'Contrast', type: 'contrast', hex: '#294f86' },
  { name: 'Volupus Pink', brand: 'Citadel', range: 'Contrast', type: 'contrast', hex: '#8e2049' },
  { name: 'Warp Lightning', brand: 'Citadel', range: 'Contrast', type: 'contrast', hex: '#2f8c25' },
  { name: 'Wyldwood', brand: 'Citadel', range: 'Contrast', type: 'contrast', hex: '#4b3a2e' },
];

export const CITADEL_DRY: PaintPreset[] = [
  { name: 'Astorath Red', brand: 'Citadel', range: 'Dry', type: 'dry', hex: '#a91a1e' },
  { name: 'Changeling Pink', brand: 'Citadel', range: 'Dry', type: 'dry', hex: '#f0a0c0' },
  { name: 'Dawnstone', brand: 'Citadel', range: 'Dry', type: 'dry', hex: '#70756e' },
  { name: 'Eldar Flesh', brand: 'Citadel', range: 'Dry', type: 'dry', hex: '#e8c07a' },
  { name: 'Etherium Blue', brand: 'Citadel', range: 'Dry', type: 'dry', hex: '#97afc5' },
  { name: 'Golden Griffon', brand: 'Citadel', range: 'Dry', type: 'dry', hex: '#c8a830' },
  { name: 'Golgfag Brown', brand: 'Citadel', range: 'Dry', type: 'dry', hex: '#8a5028' },
  { name: 'Hexos Palesun', brand: 'Citadel', range: 'Dry', type: 'dry', hex: '#fff468' },
  { name: 'Hoeth Blue', brand: 'Citadel', range: 'Dry', type: 'dry', hex: '#4c78af' },
  { name: 'Imrik Blue', brand: 'Citadel', range: 'Dry', type: 'dry', hex: '#2080a0' },
  { name: 'Longbeard Grey', brand: 'Citadel', range: 'Dry', type: 'dry', hex: '#c0c0b0' },
  { name: 'Lucius Lilac', brand: 'Citadel', range: 'Dry', type: 'dry', hex: '#b090c0' },
  { name: 'Necron Compound', brand: 'Citadel', range: 'Dry', type: 'dry', hex: '#b4b8b0' },
  { name: 'Niblet Green', brand: 'Citadel', range: 'Dry', type: 'dry', hex: '#68a830' },
  { name: 'Nurgling Green', brand: 'Citadel', range: 'Dry', type: 'dry', hex: '#849b62' },
  { name: 'Praxeti White', brand: 'Citadel', range: 'Dry', type: 'dry', hex: '#ffffff' },
  { name: 'Ryza Rust', brand: 'Citadel', range: 'Dry', type: 'dry', hex: '#e87020' },
  { name: 'Sigmarite', brand: 'Citadel', range: 'Dry', type: 'dry', hex: '#c8a040' },
  { name: 'Skink Blue', brand: 'Citadel', range: 'Dry', type: 'dry', hex: '#50a0c0' },
  { name: 'Stormfang', brand: 'Citadel', range: 'Dry', type: 'dry', hex: '#5090b0' },
  { name: 'Sylvaneth Bark', brand: 'Citadel', range: 'Dry', type: 'dry', hex: '#4a3828' },
  { name: 'Terminatus Stone', brand: 'Citadel', range: 'Dry', type: 'dry', hex: '#c0b898' },
  { name: 'Thunderhawk Blue', brand: 'Citadel', range: 'Dry', type: 'dry', hex: '#417074' },
  { name: 'Tyrant Skull', brand: 'Citadel', range: 'Dry', type: 'dry', hex: '#c8c0a0' },
  { name: 'Underhive Ash', brand: 'Citadel', range: 'Dry', type: 'dry', hex: '#b8b098' },
  { name: 'Wrack White', brand: 'Citadel', range: 'Dry', type: 'dry', hex: '#d0d8d0' },
];

export const CITADEL_TECHNICAL: PaintPreset[] = [
  { name: 'Ardcoat', brand: 'Citadel', range: 'Technical', type: 'technical', hex: '#e0e0e0' },
  { name: 'Astrogranite', brand: 'Citadel', range: 'Technical', type: 'technical', hex: '#6a6a6a' },
  { name: 'Astrogranite Debris', brand: 'Citadel', range: 'Technical', type: 'technical', hex: '#808080' },
  { name: 'Blood for the Blood God', brand: 'Citadel', range: 'Technical', type: 'technical', hex: '#8a0000' },
  { name: 'Lahmian Medium', brand: 'Citadel', range: 'Technical', type: 'technical', hex: '#e0e0e0' },
  { name: 'Martian Ironcrust', brand: 'Citadel', range: 'Technical', type: 'technical', hex: '#a04020' },
  { name: 'Martian Ironearth', brand: 'Citadel', range: 'Technical', type: 'technical', hex: '#c05030' },
  { name: 'Mordant Earth', brand: 'Citadel', range: 'Technical', type: 'technical', hex: '#1a1a1a' },
  { name: 'Nihilakh Oxide', brand: 'Citadel', range: 'Technical', type: 'technical', hex: '#60c0a0' },
  { name: 'Nurgle\'s Rot', brand: 'Citadel', range: 'Technical', type: 'technical', hex: '#9aaa1a' },
  { name: 'Stirland Battlemire', brand: 'Citadel', range: 'Technical', type: 'technical', hex: '#4a3820' },
  { name: 'Stirland Mud', brand: 'Citadel', range: 'Technical', type: 'technical', hex: '#5a4828' },
  { name: 'Stormshield', brand: 'Citadel', range: 'Technical', type: 'technical', hex: '#e0e0e0' },
  { name: 'Tesseract Glow', brand: 'Citadel', range: 'Technical', type: 'technical', hex: '#40e040' },
  { name: 'Typhus Corrosion', brand: 'Citadel', range: 'Technical', type: 'technical', hex: '#3a3020' },
  { name: 'Valhallan Blizzard', brand: 'Citadel', range: 'Technical', type: 'technical', hex: '#f0f0f0' },
];
