import type { PaintPreset } from './paints-citadel-base';

export const ARMY_PAINTER: PaintPreset[] = [
  { name: 'Matt White', brand: 'Army Painter', range: 'Warpaints', type: 'base', hex: '#ffffff' },
  { name: 'Skeleton Bone', brand: 'Army Painter', range: 'Warpaints', type: 'base', hex: '#dbc8a0' },
  { name: 'Daemonic Yellow', brand: 'Army Painter', range: 'Warpaints', type: 'base', hex: '#f8d800' },
  { name: 'Desert Yellow', brand: 'Army Painter', range: 'Warpaints', type: 'base', hex: '#c8a848' },
  { name: 'Lava Orange', brand: 'Army Painter', range: 'Warpaints', type: 'base', hex: '#e85820' },
  { name: 'Fire Lizard', brand: 'Army Painter', range: 'Warpaints', type: 'base', hex: '#e84820' },
  { name: 'Pure Red', brand: 'Army Painter', range: 'Warpaints', type: 'base', hex: '#c01010' },
  { name: 'Dragon Red', brand: 'Army Painter', range: 'Warpaints', type: 'base', hex: '#8a0808' },
  { name: 'Crusted Sore', brand: 'Army Painter', range: 'Warpaints', type: 'base', hex: '#6a0808' },
  { name: 'Pixie Pink', brand: 'Army Painter', range: 'Warpaints', type: 'base', hex: '#e070a0' },
  { name: 'Alien Purple', brand: 'Army Painter', range: 'Warpaints', type: 'base', hex: '#5a1878' },
  { name: 'Lich Purple', brand: 'Army Painter', range: 'Warpaints', type: 'base', hex: '#3a1050' },
  { name: 'Ultramarine Blue', brand: 'Army Painter', range: 'Warpaints', type: 'base', hex: '#1a3090' },
  { name: 'Crystal Blue', brand: 'Army Painter', range: 'Warpaints', type: 'base', hex: '#3080c0' },
  { name: 'Electric Blue', brand: 'Army Painter', range: 'Warpaints', type: 'base', hex: '#0088d0' },
  { name: 'Deep Blue', brand: 'Army Painter', range: 'Warpaints', type: 'base', hex: '#0a1850' },
  { name: 'Hydra Turquoise', brand: 'Army Painter', range: 'Warpaints', type: 'base', hex: '#008888' },
  { name: 'Voidshield Blue', brand: 'Army Painter', range: 'Warpaints', type: 'base', hex: '#2060a0' },
  { name: 'Greenskin', brand: 'Army Painter', range: 'Warpaints', type: 'base', hex: '#3a8830' },
  { name: 'Goblin Green', brand: 'Army Painter', range: 'Warpaints', type: 'base', hex: '#48a030' },
  { name: 'Angel Green', brand: 'Army Painter', range: 'Warpaints', type: 'base', hex: '#004828' },
  { name: 'Army Green', brand: 'Army Painter', range: 'Warpaints', type: 'base', hex: '#3a5020' },
  { name: 'Jungle Green', brand: 'Army Painter', range: 'Warpaints', type: 'base', hex: '#006838' },
  { name: 'Mouldy Clothes', brand: 'Army Painter', range: 'Warpaints', type: 'base', hex: '#6a7838' },
  { name: 'Leather Brown', brand: 'Army Painter', range: 'Warpaints', type: 'base', hex: '#7a5830' },
  { name: 'Monster Brown', brand: 'Army Painter', range: 'Warpaints', type: 'base', hex: '#5a3818' },
  { name: 'Fur Brown', brand: 'Army Painter', range: 'Warpaints', type: 'base', hex: '#6a4020' },
  { name: 'Oak Brown', brand: 'Army Painter', range: 'Warpaints', type: 'base', hex: '#4a2810' },
  { name: 'Dirt Splatter', brand: 'Army Painter', range: 'Warpaints', type: 'base', hex: '#8a6838' },
  { name: 'Arid Earth', brand: 'Army Painter', range: 'Warpaints', type: 'base', hex: '#b09060' },
  { name: 'Tanned Flesh', brand: 'Army Painter', range: 'Warpaints', type: 'base', hex: '#c89068' },
  { name: 'Barbarian Flesh', brand: 'Army Painter', range: 'Warpaints', type: 'base', hex: '#d8a878' },
  { name: 'Dark Stone', brand: 'Army Painter', range: 'Warpaints', type: 'base', hex: '#484038' },
  { name: 'Ash Grey', brand: 'Army Painter', range: 'Warpaints', type: 'base', hex: '#909090' },
  { name: 'Uniform Grey', brand: 'Army Painter', range: 'Warpaints', type: 'base', hex: '#606868' },
  { name: 'Necromancer Cloak', brand: 'Army Painter', range: 'Warpaints', type: 'base', hex: '#404848' },
  { name: 'Fog Grey', brand: 'Army Painter', range: 'Warpaints', type: 'base', hex: '#b8c0c0' },
  { name: 'Matt Black', brand: 'Army Painter', range: 'Warpaints', type: 'base', hex: '#0a0a0a' },
  { name: 'Gun Metal', brand: 'Army Painter', range: 'Warpaints', type: 'base', hex: '#586068' },
  { name: 'Plate Mail Metal', brand: 'Army Painter', range: 'Warpaints', type: 'base', hex: '#a0a8b0' },
  { name: 'Shining Silver', brand: 'Army Painter', range: 'Warpaints', type: 'base', hex: '#c0c8d0' },
  { name: 'Greedy Gold', brand: 'Army Painter', range: 'Warpaints', type: 'base', hex: '#c0a030' },
  { name: 'Weapon Bronze', brand: 'Army Painter', range: 'Warpaints', type: 'base', hex: '#907030' },
  { name: 'Rough Iron', brand: 'Army Painter', range: 'Warpaints', type: 'base', hex: '#484848' },
  { name: 'True Copper', brand: 'Army Painter', range: 'Warpaints', type: 'base', hex: '#b07838' },
  { name: 'Dark Tone', brand: 'Army Painter', range: 'Quickshade Wash', type: 'shade', hex: '#1a1008' },
  { name: 'Strong Tone', brand: 'Army Painter', range: 'Quickshade Wash', type: 'shade', hex: '#5a3601' },
  { name: 'Soft Tone', brand: 'Army Painter', range: 'Quickshade Wash', type: 'shade', hex: '#c8a060' },
  { name: 'Blue Tone', brand: 'Army Painter', range: 'Quickshade Wash', type: 'shade', hex: '#1a4080' },
  { name: 'Green Tone', brand: 'Army Painter', range: 'Quickshade Wash', type: 'shade', hex: '#1a6030' },
  { name: 'Red Tone', brand: 'Army Painter', range: 'Quickshade Wash', type: 'shade', hex: '#8a1818' },
  { name: 'Purple Tone', brand: 'Army Painter', range: 'Quickshade Wash', type: 'shade', hex: '#5a1860' },
  { name: 'Flesh Wash', brand: 'Army Painter', range: 'Quickshade Wash', type: 'shade', hex: '#c08050' },
];

export const SPEED_PAINTS: PaintPreset[] = [
  { name: 'Absolution Green', brand: 'Army Painter', range: 'Speedpaint', type: 'contrast', hex: '#004828' },
  { name: 'Broadsword Silver', brand: 'Army Painter', range: 'Speedpaint', type: 'contrast', hex: '#a0a8b0' },
  { name: 'Burning Bright', brand: 'Army Painter', range: 'Speedpaint', type: 'contrast', hex: '#e85820' },
  { name: 'Butcher Red', brand: 'Army Painter', range: 'Speedpaint', type: 'contrast', hex: '#8a0808' },
  { name: 'Crusader Skin', brand: 'Army Painter', range: 'Speedpaint', type: 'contrast', hex: '#d0a070' },
  { name: 'Dark Wood', brand: 'Army Painter', range: 'Speedpaint', type: 'contrast', hex: '#3a2010' },
  { name: 'Doomfire Magenta', brand: 'Army Painter', range: 'Speedpaint', type: 'contrast', hex: '#a01050' },
  { name: 'Dwarf Skin', brand: 'Army Painter', range: 'Speedpaint', type: 'contrast', hex: '#c48a5e' },
  { name: 'Enchanted Steel', brand: 'Army Painter', range: 'Speedpaint', type: 'contrast', hex: '#707880' },
  { name: 'Gravelord Grey', brand: 'Army Painter', range: 'Speedpaint', type: 'contrast', hex: '#606868' },
  { name: 'Hatchet Copper', brand: 'Army Painter', range: 'Speedpaint', type: 'contrast', hex: '#b07030' },
  { name: 'Holy White', brand: 'Army Painter', range: 'Speedpaint', type: 'contrast', hex: '#e8e8e8' },
  { name: 'Icy Storm', brand: 'Army Painter', range: 'Speedpaint', type: 'contrast', hex: '#80b8d0' },
  { name: 'Lawful Blue', brand: 'Army Painter', range: 'Speedpaint', type: 'contrast', hex: '#2050a0' },
  { name: 'Malignant Green', brand: 'Army Painter', range: 'Speedpaint', type: 'contrast', hex: '#3a8830' },
  { name: 'Medium Armor', brand: 'Army Painter', range: 'Speedpaint', type: 'contrast', hex: '#c8a830' },
  { name: 'Midnight Cloak', brand: 'Army Painter', range: 'Speedpaint', type: 'contrast', hex: '#0a1838' },
  { name: 'Orc Skin', brand: 'Army Painter', range: 'Speedpaint', type: 'contrast', hex: '#4a7830' },
  { name: 'Pallid Bone', brand: 'Army Painter', range: 'Speedpaint', type: 'contrast', hex: '#dbc8a0' },
  { name: 'Plagueling', brand: 'Army Painter', range: 'Speedpaint', type: 'contrast', hex: '#8aa830' },
  { name: 'Poppy Red', brand: 'Army Painter', range: 'Speedpaint', type: 'contrast', hex: '#c01010' },
  { name: 'Royal Cloak', brand: 'Army Painter', range: 'Speedpaint', type: 'contrast', hex: '#5a1878' },
  { name: 'Runic Grey', brand: 'Army Painter', range: 'Speedpaint', type: 'contrast', hex: '#909090' },
  { name: 'Slaughter Red', brand: 'Army Painter', range: 'Speedpaint', type: 'contrast', hex: '#a01010' },
  { name: 'Slimy Green', brand: 'Army Painter', range: 'Speedpaint', type: 'contrast', hex: '#5cb830' },
  { name: 'Sludge Brown', brand: 'Army Painter', range: 'Speedpaint', type: 'contrast', hex: '#5a3818' },
  { name: 'Speed Metal', brand: 'Army Painter', range: 'Speedpaint', type: 'contrast', hex: '#c0c0c0' },
  { name: 'Sunrise Orange', brand: 'Army Painter', range: 'Speedpaint', type: 'contrast', hex: '#e88040' },
  { name: 'Turbo Dork', brand: 'Army Painter', range: 'Speedpaint', type: 'contrast', hex: '#008888' },
  { name: 'Wicked Purple', brand: 'Army Painter', range: 'Speedpaint', type: 'contrast', hex: '#4a1860' },
  { name: 'Zealot Yellow', brand: 'Army Painter', range: 'Speedpaint', type: 'contrast', hex: '#f0c010' },
  { name: 'Hardened Leather', brand: 'Army Painter', range: 'Speedpaint', type: 'contrast', hex: '#7a5830' },
  { name: 'Mega Stone', brand: 'Army Painter', range: 'Speedpaint', type: 'contrast', hex: '#a09880' },
  { name: 'Highlord Blue', brand: 'Army Painter', range: 'Speedpaint', type: 'contrast', hex: '#3070c0' },
  { name: 'Crypt Shade', brand: 'Army Painter', range: 'Speedpaint', type: 'contrast', hex: '#1a1a1a' },
  { name: 'Living Flesh', brand: 'Army Painter', range: 'Speedpaint', type: 'contrast', hex: '#d8b090' },
];
