import { PaintTimer, RandomPicker, ShoppingList, CsvImport, ShareCollection, Glossary } from '../components/Tools';
import PaintMatcher from '../components/PaintMatcher';
import { addHachetteCollection } from '../db/hachette-collection';
import { db } from '../db';
import { useState } from 'react';
import { useLiveQuery } from 'dexie-react-hooks';

export default function Tools() {
  const [hachetteStatus, setHachetteStatus] = useState('');
  const models = useLiveQuery(() => db.models.toArray()) ?? [];
  const paints = useLiveQuery(() => db.paints.toArray()) ?? [];

  const exportPdf = () => {
    const w = window.open('', '_blank');
    if (!w) return;
    const painted = models.filter(m => m.status === 'painted' || m.status === 'based');
    const html = `<html><head><title>Grimdeck Collection</title><style>body{font-family:Georgia,serif;max-width:700px;margin:40px auto;color:#1a1a1a}h1{color:#8a6a1a;border-bottom:2px solid #d4af37;padding-bottom:8px}table{width:100%;border-collapse:collapse;margin:16px 0;font-size:13px}th,td{border:1px solid #ddd;padding:6px 10px;text-align:left}th{background:#f5f0e0;color:#6a5010}tr:nth-child(even){background:#faf8f4}.stat{font-size:12px;color:#888;margin-top:4px}@media print{body{margin:0}}</style></head><body>` +
      `<h1>Grimdeck Collection</h1><p>${models.length} units · ${models.reduce((s,m)=>s+m.quantity,0)} minis · ${painted.reduce((s,m)=>s+m.quantity,0)} painted · ${paints.length} paints</p>` +
      `<h2>Models</h2><table><tr><th>Name</th><th>Faction</th><th>Qty</th><th>Status</th><th>Points</th></tr>` +
      models.map(m => `<tr><td>${m.name}</td><td>${m.faction}</td><td>${m.quantity}</td><td>${m.status}</td><td>${m.points || '-'}</td></tr>`).join('') +
      `</table><h2>Paints (${paints.length})</h2><table><tr><th>Name</th><th>Brand</th><th>Type</th><th>Color</th></tr>` +
      paints.map(p => `<tr><td>${p.name}</td><td>${p.brand}</td><td>${p.type}</td><td><span style="display:inline-block;width:14px;height:14px;background:${p.hexColor};border-radius:3px;vertical-align:middle"></span> ${p.hexColor}</td></tr>`).join('') +
      `</table><div class="stat">Generated by Grimdeck · ${new Date().toLocaleDateString()}</div></body></html>`;
    w.document.write(html);
    w.document.close();
    setTimeout(() => w.print(), 500);
  };

  const clearHachette = async () => {
    const all = await db.models.toArray();
    const hachette = all.filter(m => m.notes?.includes('Hachette') || m.manufacturer === 'Games Workshop (Hachette)');
    for (const m of hachette) await db.models.delete(m.id!);
    setHachetteStatus(`🗑 Removed ${hachette.length} Hachette models`);
  };

  const importHachette = async () => {
    await clearHachette();
    setHachetteStatus('⏳ Adding fresh...');
    const count = await addHachetteCollection();
    setHachetteStatus(`Added ${count} models (old duplicates cleared)`);
  };

  return (
    <div>
      <div className="page-header" style={{ paddingTop: 48 }}>
        <h2>🧰 Tools</h2>
      </div>

      {/* Hachette Import */}
      <div className="tool-card" style={{ marginBottom: 16 }}>
        <h3>📰 Hachette Combat Patrol Collection</h3>
        <p className="settings-desc">Import all models from Hachette Combat Patrol magazine Issues 1-72. Clears old imports first to avoid duplicates.</p>
        <div style={{ display: 'flex', gap: 8 }}>
          <button className="btn btn-primary" onClick={importHachette}>Import Issues 1-72 (clean)</button>
          <button className="btn btn-danger btn-sm" onClick={clearHachette}>Remove Hachette models</button>
        </div>
        {hachetteStatus && <p style={{ marginTop: 8, fontSize: '0.85rem' }}>{hachetteStatus}</p>}
      </div>

      <div className="tools-grid">
        <PaintMatcher />
        <PaintTimer />
        <RandomPicker />
        <ShoppingList />
        <ShareCollection />
        <CsvImport />
        <Glossary />
        <div className="tool-card">
          <h3>📄 Export Collection</h3>
          <p className="settings-desc">Generate a printable PDF of your full collection and paint inventory.</p>
          <button className="btn btn-sm btn-primary" onClick={exportPdf}>Print / Save as PDF</button>
        </div>
      </div>
    </div>
  );
}
